/**
 * Textbook recommendation data for high school math (2022 revised curriculum).
 * Converted from source: data/교재.txt
 */

export interface TextbookData {
  name: string;
  publisher: string;
  category: string; // "기초유형", "개념서", "유형서", "심화서", etc.
  difficulty: number; // 1-5 stars
  description: string;
  targetLevel: "lower" | "middle" | "upper";
}

export const TEXTBOOK_DATA: TextbookData[] = [
  // ============================================
  // 하위권 (5등급 이하 → 3~4등급 목표)
  // ============================================
  {
    name: "베이직쎈",
    publisher: "좋은책신사고",
    category: "기초유형",
    difficulty: 1,
    description: "쎈의 가장 쉬운 버전, A단계 집중",
    targetLevel: "lower",
  },
  {
    name: "풍산자 개념완성",
    publisher: "지학사",
    category: "개념서",
    difficulty: 1,
    description: "개념을 가장 쉽게 설명, 주제별 정리",
    targetLevel: "lower",
  },
  {
    name: "개념+유형 개념편",
    publisher: "비상교육",
    category: "개념서",
    difficulty: 1,
    description: "기초 개념 이해와 유형 반복 학습",
    targetLevel: "lower",
  },
  {
    name: "라이트쎈",
    publisher: "좋은책신사고",
    category: "기본유형",
    difficulty: 2,
    description: "쎈 C단계 생략, 부담 없는 분량",
    targetLevel: "lower",
  },
  {
    name: "체크체크",
    publisher: "천재교육",
    category: "개념서",
    difficulty: 1,
    description: "교과서 기반, 기초 문제 위주",
    targetLevel: "lower",
  },
  {
    name: "빨리 이해하는 수학",
    publisher: "동아출판",
    category: "개념서",
    difficulty: 1,
    description: "짧은 설명, 빠른 개념 이해",
    targetLevel: "lower",
  },
  {
    name: "풍산자 반복수학",
    publisher: "지학사",
    category: "연산/유형",
    difficulty: 1,
    description: "같은 유형 반복으로 체화",
    targetLevel: "lower",
  },
  {
    name: "개념쎈",
    publisher: "좋은책신사고",
    category: "개념서",
    difficulty: 2,
    description: "개념 설명 + 기본 문제",
    targetLevel: "lower",
  },
  {
    name: "개념원리",
    publisher: "개념원리",
    category: "개념서",
    difficulty: 2,
    description: "가장 많이 사용되는 기본 개념서",
    targetLevel: "lower",
  },
  {
    name: "개념+유형 라이트",
    publisher: "비상교육",
    category: "기본유형",
    difficulty: 2,
    description: "기초 유형 문제 반복 연습",
    targetLevel: "lower",
  },
  {
    name: "우공비",
    publisher: "좋은책신사고",
    category: "개념서",
    difficulty: 2,
    description: "이미지로 개념 정리, 시각적 학습",
    targetLevel: "lower",
  },
  {
    name: "빨리 강해지는 수학",
    publisher: "동아출판",
    category: "기본유형",
    difficulty: 2,
    description: "핵심 유형만 선별 수록",
    targetLevel: "lower",
  },
  {
    name: "신 수학의 바이블",
    publisher: "이투스북",
    category: "개념서",
    difficulty: 2,
    description: "친절한 개념 설명, 단계별 구성",
    targetLevel: "lower",
  },
  {
    name: "우공비Q 표준편",
    publisher: "좋은책신사고",
    category: "기본유형",
    difficulty: 2,
    description: "표준 난이도 유형 문제",
    targetLevel: "lower",
  },
  {
    name: "EBS 수능특강",
    publisher: "EBS",
    category: "개념+유형",
    difficulty: 2,
    description: "수능 연계, 기본 개념 정리",
    targetLevel: "lower",
  },
  {
    name: "마플교과서",
    publisher: "희망에듀",
    category: "개념서",
    difficulty: 2,
    description: "교과서 개념 + 빈출 유형",
    targetLevel: "lower",
  },
  {
    name: "개념원리 RPM",
    publisher: "개념원리",
    category: "기본유형",
    difficulty: 2,
    description: "개념원리와 연계, 유형별 분류",
    targetLevel: "lower",
  },
  {
    name: "풍산자 필수유형",
    publisher: "지학사",
    category: "유형서",
    difficulty: 2,
    description: "출제 빈도 높은 문제만 선별",
    targetLevel: "lower",
  },
  {
    name: "숨마쿰라우데 스타트업",
    publisher: "이룸이앤비",
    category: "기초개념",
    difficulty: 2,
    description: "개념부터 체계적 구성",
    targetLevel: "lower",
  },
  {
    name: "굿비",
    publisher: "이룸이앤비",
    category: "개념+유형",
    difficulty: 2,
    description: "9강으로 끝내는 구성, 부담 적음",
    targetLevel: "lower",
  },

  // ============================================
  // 중위권 (3~4등급 → 2등급 안정화 목표)
  // ============================================
  {
    name: "쎈",
    publisher: "좋은책신사고",
    category: "유형서",
    difficulty: 3,
    description: "A/B/C 3단계, 1,500문제 이상",
    targetLevel: "middle",
  },
  {
    name: "개념원리 RPM",
    publisher: "개념원리",
    category: "유형서",
    difficulty: 2,
    description: "유형별 4개 이상 문제, 체계적 분류",
    targetLevel: "middle",
  },
  {
    name: "마플 시너지",
    publisher: "희망에듀",
    category: "유형서",
    difficulty: 3,
    description: "쎈의 1.5~2배 문제량, 양치기 최적화",
    targetLevel: "middle",
  },
  {
    name: "개념+유형 파워편",
    publisher: "비상교육",
    category: "유형서",
    difficulty: 3,
    description: "응용 유형 중심, 단계별 학습",
    targetLevel: "middle",
  },
  {
    name: "숨마쿰라우데",
    publisher: "이룸이앤비",
    category: "개념서",
    difficulty: 3,
    description: "깊은 개념 설명, 발전 예제 포함",
    targetLevel: "middle",
  },
  {
    name: "수학의 정석 기본편",
    publisher: "성지출판",
    category: "개념서",
    difficulty: 3,
    description: "전통의 명품 개념서",
    targetLevel: "middle",
  },
  {
    name: "수학의 바이블",
    publisher: "이투스북",
    category: "개념서",
    difficulty: 3,
    description: "일반 개념서보다 상세한 설명",
    targetLevel: "middle",
  },
  {
    name: "유형아작",
    publisher: "비상교육",
    category: "유형서",
    difficulty: 3,
    description: "유형별 집중 훈련",
    targetLevel: "middle",
  },
  {
    name: "A급 원리해설",
    publisher: "디딤돌",
    category: "유형서",
    difficulty: 3,
    description: "원리 중심 해설, 사고력 강화",
    targetLevel: "middle",
  },
  {
    name: "우공비Q 발전편",
    publisher: "좋은책신사고",
    category: "응용유형",
    difficulty: 3,
    description: "발전된 응용 문제 수록",
    targetLevel: "middle",
  },
  {
    name: "최상위 라이트",
    publisher: "디딤돌",
    category: "준심화",
    difficulty: 3,
    description: "심화 입문용, 부담 적은 난이도",
    targetLevel: "middle",
  },
  {
    name: "절대등급",
    publisher: "능률",
    category: "준심화",
    difficulty: 3,
    description: "내신 상위권 대비, 서술형 강화",
    targetLevel: "middle",
  },
  {
    name: "최고득점",
    publisher: "천재교육",
    category: "준심화",
    difficulty: 3,
    description: "고득점 목표 문제 수록",
    targetLevel: "middle",
  },
  {
    name: "자이스토리",
    publisher: "수경출판",
    category: "기출문제",
    difficulty: 3,
    description: "모든 기출 수록, 연도별/유형별 정리",
    targetLevel: "middle",
  },
  {
    name: "마더텅 기출",
    publisher: "마더텅",
    category: "기출문제",
    difficulty: 3,
    description: "상세한 해설, 기출 총정리",
    targetLevel: "middle",
  },
  {
    name: "1등급 만들기",
    publisher: "미래엔",
    category: "기출문제",
    difficulty: 3,
    description: "기출 분석 문제집, 483제",
    targetLevel: "middle",
  },
  {
    name: "올백 1등급 MASTER",
    publisher: "천재교육",
    category: "고난도기출",
    difficulty: 3,
    description: "910제 고난도 기출",
    targetLevel: "middle",
  },
  {
    name: "플래티넘",
    publisher: "-",
    category: "내신기출",
    difficulty: 3,
    description: "학교별 내신 기출 모음",
    targetLevel: "middle",
  },
  {
    name: "EBS 수능완성",
    publisher: "EBS",
    category: "실전문제",
    difficulty: 3,
    description: "수능 연계, 실전 감각 훈련",
    targetLevel: "middle",
  },
  {
    name: "너기출",
    publisher: "-",
    category: "기출문제",
    difficulty: 3,
    description: "선별된 기출, 가볍게 풀기 좋음",
    targetLevel: "middle",
  },

  // ============================================
  // 상위권 (1~2등급 → 1등급 안정화/만점 목표)
  // ============================================
  {
    name: "블랙라벨",
    publisher: "진학사",
    category: "심화서",
    difficulty: 4,
    description: "1등급 명품 문제집, 70~90p 얇은 구성",
    targetLevel: "upper",
  },
  {
    name: "일품",
    publisher: "좋은책신사고",
    category: "심화서",
    difficulty: 4,
    description: "쎈 C단계와 비슷하거나 약간 높음",
    targetLevel: "upper",
  },
  {
    name: "고쟁이",
    publisher: "이투스북",
    category: "심화서",
    difficulty: 4,
    description: "5개년 기출 분석, 최다빈출 문제",
    targetLevel: "upper",
  },
  {
    name: "일등급 수학",
    publisher: "수경출판",
    category: "심화서",
    difficulty: 4,
    description: "사고력 요구 문제, 심화 입문용",
    targetLevel: "upper",
  },
  {
    name: "최상위",
    publisher: "디딤돌",
    category: "심화서",
    difficulty: 5,
    description: "증명 문제 많음, 적절한 힌트 제공",
    targetLevel: "upper",
  },
  {
    name: "수학의 정석 실력편",
    publisher: "성지출판",
    category: "심화서",
    difficulty: 5,
    description: "수리논술 대비 수준, 사고 확장",
    targetLevel: "upper",
  },
  {
    name: "올림포스 고난도",
    publisher: "천재교육",
    category: "심화서",
    difficulty: 4,
    description: "내신 킬러 문항 집중",
    targetLevel: "upper",
  },
  {
    name: "수학의 고수",
    publisher: "능률",
    category: "심화서",
    difficulty: 4,
    description: "내신 고득점 심화 학습",
    targetLevel: "upper",
  },
  {
    name: "최고수준",
    publisher: "천재교육",
    category: "심화서",
    difficulty: 4,
    description: "최고 난이도 문제 수록",
    targetLevel: "upper",
  },
  {
    name: "에이급 수학",
    publisher: "에이급",
    category: "극심화",
    difficulty: 5,
    description: "경시대회 수준, 극고난도",
    targetLevel: "upper",
  },
  {
    name: "531 프로젝트",
    publisher: "이투스북",
    category: "심화서",
    difficulty: 4,
    description: "5지선다→3지선다→1답 구성",
    targetLevel: "upper",
  },
  {
    name: "TOT",
    publisher: "-",
    category: "심화서",
    difficulty: 4,
    description: "Top of the Top, 최상위 문제",
    targetLevel: "upper",
  },
  {
    name: "마플",
    publisher: "희망에듀",
    category: "기출문제",
    difficulty: 4,
    description: "고난도 기출 + 변형 문제",
    targetLevel: "upper",
  },
  {
    name: "킬링캠프",
    publisher: "-",
    category: "실전대비",
    difficulty: 5,
    description: "수능 직전 마무리, 고난도 집중",
    targetLevel: "upper",
  },
  {
    name: "일타에듀 고난도 모의고사",
    publisher: "-",
    category: "실전대비",
    difficulty: 5,
    description: "킬러 문제 깊이 있는 접근",
    targetLevel: "upper",
  },
  {
    name: "뉴런",
    publisher: "-",
    category: "심화서",
    difficulty: 4,
    description: "신경망처럼 연결된 개념 학습",
    targetLevel: "upper",
  },
  {
    name: "프로메쓰",
    publisher: "-",
    category: "내신기출",
    difficulty: 4,
    description: "고등학교 내신 기출 분석",
    targetLevel: "upper",
  },
  {
    name: "수학대왕",
    publisher: "-",
    category: "AI학습",
    difficulty: 3,
    description: "AI 실력 분석, 맞춤 문제 제공",
    targetLevel: "upper",
  },
  {
    name: "EBS 수능특강 변형문제",
    publisher: "사설",
    category: "변형문제",
    difficulty: 4,
    description: "EBS 연계 변형, 실전 감각",
    targetLevel: "upper",
  },
  {
    name: "학교별 기출문제",
    publisher: "-",
    category: "내신기출",
    difficulty: 4,
    description: "족보닷컴, 기출로 등 활용",
    targetLevel: "upper",
  },
];
