/**
 * 상점 아이템 시드 데이터
 * 실행: npx tsx scripts/seed-shop-items.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ITEMS = [
  // ── FRAME (아바타 테두리) ──
  {
    category: 'FRAME' as const,
    name: '골드 프레임',
    description: '빛나는 금색 테두리',
    price: 50,
    value: { border: '2px solid #f59e0b', boxShadow: '0 0 4px rgba(245,158,11,0.4)' },
    sortOrder: 1,
    levelReq: 1,
  },
  {
    category: 'FRAME' as const,
    name: '네온 블루',
    description: '시원한 파란빛 네온 효과',
    price: 100,
    value: { border: '2px solid #60a5fa', boxShadow: '0 0 8px rgba(96,165,250,0.6)' },
    sortOrder: 2,
    levelReq: 2,
  },
  {
    category: 'FRAME' as const,
    name: '에메랄드',
    description: '신비로운 녹색 빛',
    price: 150,
    value: { border: '2px solid #34d399', boxShadow: '0 0 8px rgba(52,211,153,0.5)' },
    sortOrder: 3,
    levelReq: 2,
  },
  {
    category: 'FRAME' as const,
    name: '핑크 글로우',
    description: '사랑스러운 핑크 빛',
    price: 200,
    value: { border: '2px solid #f472b6', boxShadow: '0 0 10px rgba(244,114,182,0.5)' },
    sortOrder: 4,
    levelReq: 3,
  },
  {
    category: 'FRAME' as const,
    name: '불꽃 프레임',
    description: '열정 넘치는 주황빛 불꽃',
    price: 300,
    value: { border: '3px solid #f97316', boxShadow: '0 0 12px rgba(249,115,22,0.6), 0 0 4px rgba(239,68,68,0.3)' },
    sortOrder: 5,
    levelReq: 4,
  },
  {
    category: 'FRAME' as const,
    name: '다이아몬드',
    description: '최고의 등급! 눈부신 다이아몬드 빛',
    price: 500,
    value: { border: '3px solid #67e8f9', boxShadow: '0 0 14px rgba(103,232,249,0.7), 0 0 4px rgba(139,92,246,0.3)' },
    sortOrder: 6,
    levelReq: 5,
  },

  // ── BACKGROUND (프로필 카드 배경) ──
  {
    category: 'BACKGROUND' as const,
    name: '민트 그라디언트',
    description: '상쾌한 민트색 배경',
    price: 80,
    value: { background: 'linear-gradient(135deg, #ecfdf5, #ecfeff)' },
    sortOrder: 1,
    levelReq: 1,
  },
  {
    category: 'BACKGROUND' as const,
    name: '석양',
    description: '따뜻한 노을빛 배경',
    price: 120,
    value: { background: 'linear-gradient(135deg, #fff7ed, #fff1f2)' },
    sortOrder: 2,
    levelReq: 1,
  },
  {
    category: 'BACKGROUND' as const,
    name: '라벤더',
    description: '편안한 보라빛 배경',
    price: 120,
    value: { background: 'linear-gradient(135deg, #f5f3ff, #ede9fe)' },
    sortOrder: 3,
    levelReq: 2,
  },
  {
    category: 'BACKGROUND' as const,
    name: '오션 블루',
    description: '깊은 바다처럼 푸른 배경',
    price: 150,
    value: { background: 'linear-gradient(135deg, #eff6ff, #dbeafe)' },
    sortOrder: 4,
    levelReq: 2,
  },
  {
    category: 'BACKGROUND' as const,
    name: '우주',
    description: '신비로운 우주 색감',
    price: 250,
    value: { background: 'linear-gradient(135deg, #1e1b4b, #312e81)', color: '#e2e8f0' },
    sortOrder: 5,
    levelReq: 4,
  },

  // ── TITLE (칭호) ──
  {
    category: 'TITLE' as const,
    name: '수학 초보',
    description: '모두의 시작점',
    price: 30,
    value: { text: '🌱 수학 초보' },
    sortOrder: 1,
    levelReq: 1,
  },
  {
    category: 'TITLE' as const,
    name: '공부벌레',
    description: '열심히 공부하는 벌레!',
    price: 80,
    value: { text: '📚 공부벌레' },
    sortOrder: 2,
    levelReq: 1,
  },
  {
    category: 'TITLE' as const,
    name: '연산 마스터',
    description: '연산의 달인',
    price: 150,
    value: { text: '⚡ 연산 마스터' },
    sortOrder: 3,
    levelReq: 2,
  },
  {
    category: 'TITLE' as const,
    name: '끈기왕',
    description: '포기하지 않는 끈기의 소유자',
    price: 200,
    value: { text: '💪 끈기왕' },
    sortOrder: 4,
    levelReq: 3,
  },
  {
    category: 'TITLE' as const,
    name: '수학의 신',
    description: '경배하라! 수학의 신이 오셨다',
    price: 400,
    value: { text: '👑 수학의 신' },
    sortOrder: 5,
    levelReq: 5,
  },

  // ── AVATAR (아바타 포즈) ──
  {
    category: 'AVATAR' as const,
    name: '기본 자세',
    description: '차분하게 서 있는 포즈',
    price: 0,
    value: { src: '/avatars/standing.png' },
    sortOrder: 1,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '인사',
    description: '반갑게 손을 흔드는 포즈',
    price: 50,
    value: { src: '/avatars/waving.png' },
    sortOrder: 2,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '자신감',
    description: '팔짱을 끼고 당당한 포즈',
    price: 80,
    value: { src: '/avatars/arms-crossed.png' },
    sortOrder: 3,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '발표',
    description: '양손을 펼쳐 설명하는 포즈',
    price: 100,
    value: { src: '/avatars/presenting.png' },
    sortOrder: 4,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '쑥스러운',
    description: '머리 긁적이며 쑥스러워하는 포즈',
    price: 100,
    value: { src: '/avatars/thinking.png' },
    sortOrder: 5,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '산책',
    description: '여유롭게 걸어가는 포즈',
    price: 120,
    value: { src: '/avatars/casual.png' },
    sortOrder: 6,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '쉬는 중',
    description: '쪼그려 앉아 쉬는 포즈',
    price: 150,
    value: { src: '/avatars/sitting.png' },
    sortOrder: 7,
    levelReq: 3,
  },
  {
    category: 'AVATAR' as const,
    name: '최고!',
    description: '엄지척! 자신감 넘치는 포즈',
    price: 200,
    value: { src: '/avatars/thumbs-up.png' },
    sortOrder: 8,
    levelReq: 3,
  },
  {
    category: 'AVATAR' as const,
    name: '깜짝',
    description: '입을 가리고 놀라는 포즈',
    price: 300,
    value: { src: '/avatars/running.png' },
    sortOrder: 9,
    levelReq: 4,
  },

  // ── AVATAR 여학생 ──
  {
    category: 'AVATAR' as const,
    name: '수줍은 (여)',
    description: '두 손 모으고 수줍어하는 포즈',
    price: 0,
    value: { src: '/avatars/f-standing.png' },
    sortOrder: 11,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '인사 (여)',
    description: '반갑게 손을 흔드는 포즈',
    price: 50,
    value: { src: '/avatars/f-waving.png' },
    sortOrder: 12,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '궁금한 (여)',
    description: '턱에 손을 대고 생각하는 포즈',
    price: 80,
    value: { src: '/avatars/f-presenting.png' },
    sortOrder: 13,
    levelReq: 1,
  },
  {
    category: 'AVATAR' as const,
    name: '안내 (여)',
    description: '한 손으로 안내하는 포즈',
    price: 100,
    value: { src: '/avatars/f-thinking.png' },
    sortOrder: 14,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '거수경례 (여)',
    description: '씩씩하게 경례하는 포즈',
    price: 100,
    value: { src: '/avatars/f-peace.png' },
    sortOrder: 15,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '당당한 (여)',
    description: '자신감 넘치는 포즈',
    price: 120,
    value: { src: '/avatars/f-confident.png' },
    sortOrder: 16,
    levelReq: 2,
  },
  {
    category: 'AVATAR' as const,
    name: '쉬는 중 (여)',
    description: '앉아서 쉬는 편안한 포즈',
    price: 150,
    value: { src: '/avatars/f-sitting.png' },
    sortOrder: 17,
    levelReq: 3,
  },
  {
    category: 'AVATAR' as const,
    name: '하트',
    description: '머리 위로 하트를 만드는 포즈',
    price: 200,
    value: { src: '/avatars/f-heart.png' },
    sortOrder: 18,
    levelReq: 3,
  },
  {
    category: 'AVATAR' as const,
    name: '부끄러운 (여)',
    description: '양손으로 볼을 감싸는 포즈',
    price: 300,
    value: { src: '/avatars/f-cheerful.png' },
    sortOrder: 19,
    levelReq: 4,
  },

  // ── NAME_COLOR (닉네임 색상) ──
  {
    category: 'NAME_COLOR' as const,
    name: '로열 퍼플',
    description: '고귀한 보라색 닉네임',
    price: 80,
    value: { color: '#7c3aed' },
    sortOrder: 1,
    levelReq: 1,
  },
  {
    category: 'NAME_COLOR' as const,
    name: '오션 블루',
    description: '시원한 파란색 닉네임',
    price: 80,
    value: { color: '#2563eb' },
    sortOrder: 2,
    levelReq: 1,
  },
  {
    category: 'NAME_COLOR' as const,
    name: '포레스트 그린',
    description: '자연의 초록색 닉네임',
    price: 80,
    value: { color: '#059669' },
    sortOrder: 3,
    levelReq: 1,
  },
  {
    category: 'NAME_COLOR' as const,
    name: '선셋 오렌지',
    description: '따뜻한 주황색 닉네임',
    price: 120,
    value: { color: '#ea580c' },
    sortOrder: 4,
    levelReq: 2,
  },
  {
    category: 'NAME_COLOR' as const,
    name: '레인보우',
    description: '무지개빛 그라디언트 닉네임!',
    price: 300,
    value: { backgroundImage: 'linear-gradient(90deg, #ef4444, #f59e0b, #22c55e, #3b82f6, #8b5cf6)', WebkitBackgroundClip: 'text', color: 'transparent' },
    sortOrder: 5,
    levelReq: 4,
  },
];

async function main() {
  console.log('🏪 상점 아이템 시드 시작...');

  for (const item of ITEMS) {
    await prisma.shopItem.upsert({
      where: { id: `seed_${item.category}_${item.sortOrder}` },
      create: {
        id: `seed_${item.category}_${item.sortOrder}`,
        ...item,
      },
      update: {
        name: item.name,
        description: item.description,
        price: item.price,
        value: item.value,
        sortOrder: item.sortOrder,
        levelReq: item.levelReq,
      },
    });
  }

  console.log(`✅ ${ITEMS.length}개 아이템 시드 완료`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
