import type { DiagramPreset } from './types';

/** 초등학교 다이어그램 프리셋 (1~6학년) */
export const ELEMENTARY_PRESETS: DiagramPreset[] = [
  // ═══════════════════════════════════════
  // 1학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e1-1-count-numline',
    name: '수 세기 수직선',
    description: '1부터 9까지 수직선',
    schoolLevel: 'elementary',
    gradeKey: '1학년 1학기',
    chapter: '9까지의 수',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 9, step: 1, marks: [{ value: 5, label: '5', color: '#3B82F6', showDot: true }] },
  },
  {
    id: 'e1-1-shape-dot1',
    name: '모양 찾기 (3×3)',
    description: '점 배열로 여러 가지 모양 표현',
    schoolLevel: 'elementary',
    gradeKey: '1학년 1학기',
    chapter: '여러 가지 모양',
    diagramType: 'dot_array',
    defaultParams: { rows: 3, cols: 3, symbol: '●' },
  },
  {
    id: 'e1-1-shape-dot2',
    name: '모양 만들기 (2×4)',
    description: '직사각형 형태의 점 배열',
    schoolLevel: 'elementary',
    gradeKey: '1학년 1학기',
    chapter: '여러 가지 모양',
    diagramType: 'dot_array',
    defaultParams: { rows: 2, cols: 4, symbol: '●' },
  },

  // ═══════════════════════════════════════
  // 1학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e1-2-shape-tri',
    name: '세모',
    description: '기본 삼각형 도형',
    schoolLevel: 'elementary',
    gradeKey: '1학년 2학기',
    chapter: '여러 가지 모양',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: '' }, { x: 10, y: 150, label: '' }, { x: 190, y: 150, label: '' }], sides: [], angles: [] },
  },
  {
    id: 'e1-2-shape-rect',
    name: '네모',
    description: '기본 사각형 도형',
    schoolLevel: 'elementary',
    gradeKey: '1학년 2학기',
    chapter: '여러 가지 모양',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: '' }, { x: 180, y: 20, label: '' }, { x: 180, y: 140, label: '' }, { x: 20, y: 140, label: '' }], sides: [], angles: [], type: 'rectangle' },
  },
  {
    id: 'e1-2-clock-hour',
    name: '시계 (정각)',
    description: '3시 정각 시계',
    schoolLevel: 'elementary',
    gradeKey: '1학년 2학기',
    chapter: '시계 보기와 규칙 찾기',
    diagramType: 'clock_face',
    defaultParams: { hour: 3, minute: 0, showNumbers: true, label: '' },
  },
  {
    id: 'e1-2-clock-half',
    name: '시계 (30분)',
    description: '4시 30분 시계',
    schoolLevel: 'elementary',
    gradeKey: '1학년 2학기',
    chapter: '시계 보기와 규칙 찾기',
    diagramType: 'clock_face',
    defaultParams: { hour: 4, minute: 30, showNumbers: true, label: '' },
  },
  {
    id: 'e1-2-clock-quarter',
    name: '시계 (15분)',
    description: '2시 15분 시계',
    schoolLevel: 'elementary',
    gradeKey: '1학년 2학기',
    chapter: '시계 보기와 규칙 찾기',
    diagramType: 'clock_face',
    defaultParams: { hour: 2, minute: 15, showNumbers: true, label: '' },
  },

  // ═══════════════════════════════════════
  // 2학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e2-1-place-hundreds',
    name: '자릿값 (백의 자리)',
    description: '백·십·일의 자리 블록',
    schoolLevel: 'elementary',
    gradeKey: '2학년 1학기',
    chapter: '세 자리 수',
    diagramType: 'place_value',
    defaultParams: { hundreds: 2, tens: 3, ones: 5 },
  },
  {
    id: 'e2-1-shape-tri',
    name: '삼각형',
    description: '기본 삼각형',
    schoolLevel: 'elementary',
    gradeKey: '2학년 1학기',
    chapter: '여러 가지 도형',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: '' }, { x: 10, y: 150, label: '' }, { x: 190, y: 150, label: '' }], sides: [], angles: [] },
  },
  {
    id: 'e2-1-shape-quad',
    name: '사각형',
    description: '기본 사각형',
    schoolLevel: 'elementary',
    gradeKey: '2학년 1학기',
    chapter: '여러 가지 도형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: '' }, { x: 180, y: 20, label: '' }, { x: 180, y: 140, label: '' }, { x: 20, y: 140, label: '' }], sides: [], angles: [], type: 'rectangle' },
  },
  {
    id: 'e2-1-shape-circle',
    name: '원',
    description: '기본 원',
    schoolLevel: 'elementary',
    gradeKey: '2학년 1학기',
    chapter: '여러 가지 도형',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [], arcs: [] },
  },

  // ═══════════════════════════════════════
  // 2학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e2-2-graph-bar',
    name: '막대그래프 (좋아하는 과일)',
    description: '간단한 막대그래프',
    schoolLevel: 'elementary',
    gradeKey: '2학년 2학기',
    chapter: '표와 그래프',
    diagramType: 'bar_chart',
    defaultParams: { categories: ['사과', '배', '감', '포도'], values: [5, 3, 4, 6], title: '좋아하는 과일', yLabel: '명', barColor: '#3B82F6', horizontal: false },
  },
  {
    id: 'e2-2-graph-pic',
    name: '그림그래프',
    description: '기호를 사용한 그래프',
    schoolLevel: 'elementary',
    gradeKey: '2학년 2학기',
    chapter: '표와 그래프',
    diagramType: 'picture_graph',
    defaultParams: { categories: ['사과', '배', '감'], values: [3, 2, 5], symbol: '●', symbolValue: 1, title: '' },
  },

  // ═══════════════════════════════════════
  // 3학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e3-1-plane-line',
    name: '선분·반직선·직선',
    description: '선분, 반직선, 직선의 구분',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '평면도형',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 10, step: 1, marks: [{ value: 3, label: 'A' }, { value: 7, label: 'B' }] },
  },
  {
    id: 'e3-1-plane-angle',
    name: '각과 직각',
    description: '직각 표시가 있는 각도',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '평면도형',
    diagramType: 'angle_figure',
    defaultParams: { angle: 90, showProtractor: false, label: '직각', ray1Angle: 0, color: '#3B82F6' },
  },
  {
    id: 'e3-1-plane-rtri',
    name: '직각삼각형',
    description: '직각 표시가 있는 삼각형',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '평면도형',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 150, label: 'A' }, { x: 190, y: 150, label: 'B' }, { x: 10, y: 10, label: 'C' }], sides: [], angles: [{ vertex: 0, value: '90°' }] },
  },
  {
    id: 'e3-1-plane-square',
    name: '직사각형과 정사각형',
    description: '직각 표시가 있는 사각형',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '평면도형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: 'A' }, { x: 180, y: 20, label: 'B' }, { x: 180, y: 140, label: 'C' }, { x: 20, y: 140, label: 'D' }], sides: [], angles: [], type: 'rectangle' },
  },
  {
    id: 'e3-1-frac-rect',
    name: '분수 사각형 (1/3)',
    description: '3등분 중 1개 색칠',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '분수와 소수',
    diagramType: 'fraction_rect',
    defaultParams: { rows: 3, cols: 1, coloredCount: 1, count: 1, hatching: false },
  },
  {
    id: 'e3-1-frac-circle',
    name: '분수 원 (1/4)',
    description: '4등분 중 1개 색칠',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '분수와 소수',
    diagramType: 'fraction_circle',
    defaultParams: { totalParts: 4, coloredParts: 1, count: 1 },
  },
  {
    id: 'e3-1-frac-numline',
    name: '분수 수직선',
    description: '0~1 구간을 4등분한 수직선',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '분수와 소수',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 1, step: 0.25 },
  },
  {
    id: 'e3-1-decimal-numline',
    name: '소수 수직선',
    description: '0~1 구간을 10등분한 수직선',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '분수와 소수',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 1, step: 0.1 },
  },
  {
    id: 'e5-1-frac-decimal',
    name: '분수와 소수 대응',
    description: '1/2 = 0.5 수직선 대응',
    schoolLevel: 'elementary',
    gradeKey: '3학년 1학기',
    chapter: '분수와 소수',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 1, step: 0.1, marks: [{ value: 0.25, label: '1/4' }, { value: 0.5, label: '1/2', color: '#3B82F6' }, { value: 0.75, label: '3/4' }] },
  },

  // ═══════════════════════════════════════
  // 3학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e3-2-circle-basic',
    name: '원 (중심과 반지름)',
    description: '중심점과 반지름 표시',
    schoolLevel: 'elementary',
    gradeKey: '3학년 2학기',
    chapter: '원',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'r', position: 'radius' }], arcs: [] },
  },
  {
    id: 'e3-2-circle-diameter',
    name: '원 (지름)',
    description: '지름 표시',
    schoolLevel: 'elementary',
    gradeKey: '3학년 2학기',
    chapter: '원',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'd', position: 'diameter' }], arcs: [] },
  },
  {
    id: 'e3-2-circle-compass',
    name: '원 (컴퍼스 작도)',
    description: '컴퍼스로 그린 원',
    schoolLevel: 'elementary',
    gradeKey: '3학년 2학기',
    chapter: '원',
    diagramType: 'circle',
    defaultParams: { radius: 50, labels: [{ text: 'O', position: 'center' }], arcs: [] },
  },
  {
    id: 'e3-2-data-pic',
    name: '그림그래프 (자료 정리)',
    description: '기호를 사용한 그림그래프',
    schoolLevel: 'elementary',
    gradeKey: '3학년 2학기',
    chapter: '자료의 정리',
    diagramType: 'picture_graph',
    defaultParams: { categories: ['강아지', '고양이', '토끼', '햄스터'], values: [4, 3, 2, 5], symbol: '★', symbolValue: 1, title: '좋아하는 동물' },
  },
  {
    id: 'e3-2-data-pic2',
    name: '그림그래프 (기호값 2)',
    description: '기호 1개가 2명을 나타내는 그래프',
    schoolLevel: 'elementary',
    gradeKey: '3학년 2학기',
    chapter: '자료의 정리',
    diagramType: 'picture_graph',
    defaultParams: { categories: ['축구', '농구', '야구'], values: [6, 4, 8], symbol: '●', symbolValue: 2, title: '좋아하는 운동' },
  },

  // ═══════════════════════════════════════
  // 4학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e3-1-place-thousands',
    name: '자릿값 (큰 수)',
    description: '자릿값 표로 수 나타내기',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '큰 수',
    diagramType: 'place_value',
    defaultParams: { hundreds: 4, tens: 0, ones: 7 },
  },
  {
    id: 'e4-1-angle-measure',
    name: '각도 재기',
    description: '각도기로 60° 재기',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '각도',
    diagramType: 'angle_figure',
    defaultParams: { angle: 60, showProtractor: true, label: '60°', ray1Angle: 0, color: '#3B82F6' },
  },
  {
    id: 'e4-1-angle-sum',
    name: '각의 합',
    description: '30° + 45° = 75°',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '각도',
    diagramType: 'angle_figure',
    defaultParams: {
      angle: 30, showProtractor: false, label: '30°', ray1Angle: 0, color: '#3B82F6',
      additionalAngles: [{ angle: 45, label: '45°', color: '#F97316' }],
    },
  },
  {
    id: 'e4-1-angle-triangle',
    name: '삼각형 내각의 합 (180°)',
    description: '삼각형 세 내각의 합',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '각도',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: '' }, { x: 10, y: 150, label: '' }, { x: 190, y: 150, label: '' }], sides: [], angles: [{ vertex: 0, value: '60°' }, { vertex: 1, value: '60°' }, { vertex: 2, value: '60°' }] },
  },
  {
    id: 'e4-1-quad-angle-sum',
    name: '사각형 내각의 합 (360°)',
    description: '사각형 네 내각의 합',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '각도',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: '' }, { x: 170, y: 10, label: '' }, { x: 180, y: 130, label: '' }, { x: 30, y: 140, label: '' }], sides: [], angles: [{ vertex: 0, value: '80°' }, { vertex: 1, value: '100°' }, { vertex: 2, value: '90°' }, { vertex: 3, value: '90°' }], type: 'general' },
  },
  {
    id: 'e4-1-move-slide',
    name: '밀기 (평행이동)',
    description: '도형을 오른쪽으로 이동',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '평면도형의 이동',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 30, label: '' }, { x: 80, y: 30, label: '' }, { x: 80, y: 90, label: '' }, { x: 20, y: 90, label: '' }], sides: [], angles: [], type: 'rectangle' },
  },
  {
    id: 'e4-1-move-flip',
    name: '뒤집기 (대칭이동)',
    description: '도형을 뒤집어 대칭',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '평면도형의 이동',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 50, y: 20, label: '' }, { x: 10, y: 140, label: '' }, { x: 90, y: 140, label: '' }], sides: [], angles: [] },
  },
  {
    id: 'e4-1-bar-vert',
    name: '막대그래프 (세로)',
    description: '세로 막대그래프',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '막대그래프',
    diagramType: 'bar_chart',
    defaultParams: { categories: ['1반', '2반', '3반', '4반'], values: [8, 12, 6, 10], title: '반별 도서 대출 수', yLabel: '권', barColor: '#3B82F6', horizontal: false },
  },
  {
    id: 'e4-1-bar-horiz',
    name: '막대그래프 (가로)',
    description: '가로 막대그래프',
    schoolLevel: 'elementary',
    gradeKey: '4학년 1학기',
    chapter: '막대그래프',
    diagramType: 'bar_chart',
    defaultParams: { categories: ['봄', '여름', '가을', '겨울'], values: [5, 9, 7, 4], title: '좋아하는 계절', yLabel: '명', barColor: '#10B981', horizontal: true },
  },

  // ═══════════════════════════════════════
  // 4학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e4-2-tri-isosceles',
    name: '이등변삼각형',
    description: '두 변의 길이가 같은 삼각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '삼각형',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 20, y: 150, label: 'B' }, { x: 180, y: 150, label: 'C' }], sides: [{ from: 0, to: 1, label: '5cm' }, { from: 0, to: 2, label: '5cm' }], angles: [] },
  },
  {
    id: 'e4-2-tri-equilateral',
    name: '정삼각형',
    description: '세 변의 길이가 같은 삼각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '삼각형',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 13, y: 160, label: 'B' }, { x: 187, y: 160, label: 'C' }], sides: [{ from: 0, to: 1, label: '4cm' }, { from: 1, to: 2, label: '4cm' }, { from: 0, to: 2, label: '4cm' }], angles: [] },
  },
  {
    id: 'e4-2-tri-types',
    name: '예각·둔각삼각형',
    description: '예각삼각형과 둔각삼각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '삼각형',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 60, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [], angles: [{ vertex: 0, value: '120°' }] },
  },
  {
    id: 'e4-2-quad-trap',
    name: '사다리꼴',
    description: '한 쌍의 평행 변',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '사각형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 50, y: 20, label: 'A' }, { x: 150, y: 20, label: 'B' }, { x: 180, y: 130, label: 'C' }, { x: 20, y: 130, label: 'D' }], sides: [], angles: [], type: 'trapezoid' },
  },
  {
    id: 'e4-2-quad-parallel',
    name: '평행사변형',
    description: '두 쌍의 평행 변',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '사각형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 50, y: 20, label: 'A' }, { x: 170, y: 20, label: 'B' }, { x: 150, y: 130, label: 'C' }, { x: 30, y: 130, label: 'D' }], sides: [], angles: [], type: 'parallelogram' },
  },
  {
    id: 'e4-2-quad-rhombus',
    name: '마름모',
    description: '네 변의 길이가 같은 사각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '사각형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 180, y: 75, label: 'B' }, { x: 100, y: 140, label: 'C' }, { x: 20, y: 75, label: 'D' }], sides: [], angles: [], type: 'rhombus' },
  },
  {
    id: 'e4-2-quad-rect',
    name: '직사각형·정사각형',
    description: '직사각형과 정사각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '사각형',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: 'A' }, { x: 180, y: 20, label: 'B' }, { x: 180, y: 140, label: 'C' }, { x: 20, y: 140, label: 'D' }], sides: [{ from: 0, to: 1, label: '6cm' }, { from: 1, to: 2, label: '4cm' }], angles: [], type: 'rectangle' },
  },
  {
    id: 'e4-2-linegraph',
    name: '꺾은선그래프 (기온)',
    description: '월별 기온 변화',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '꺾은선그래프',
    diagramType: 'line_graph',
    defaultParams: { categories: ['3월', '4월', '5월', '6월', '7월'], datasets: [{ values: [5, 12, 18, 24, 28], label: '기온', color: '#EF4444' }], title: '월별 평균 기온', yLabel: '°C', showDots: true },
  },
  {
    id: 'e4-2-linegraph2',
    name: '꺾은선그래프 (비교)',
    description: '두 자료 비교',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '꺾은선그래프',
    diagramType: 'line_graph',
    defaultParams: { categories: ['1월', '2월', '3월', '4월'], datasets: [{ values: [3, 5, 8, 12], label: '서울', color: '#3B82F6' }, { values: [8, 10, 14, 18], label: '부산', color: '#EF4444' }], title: '', yLabel: '°C', showDots: true },
  },
  {
    id: 'e4-2-polygon-regular',
    name: '정다각형',
    description: '정오각형',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '다각형',
    diagramType: 'regular_polygon',
    defaultParams: { sides: 5, diagonals: false, sideLength: '' },
  },
  {
    id: 'e4-2-polygon-diagonal',
    name: '대각선',
    description: '오각형의 대각선',
    schoolLevel: 'elementary',
    gradeKey: '4학년 2학기',
    chapter: '다각형',
    diagramType: 'regular_polygon',
    defaultParams: { sides: 5, diagonals: true, sideLength: '' },
  },

  // ═══════════════════════════════════════
  // 5학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e5-1-area-rect',
    name: '직사각형 넓이',
    description: '가로 × 세로',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: '' }, { x: 180, y: 20, label: '' }, { x: 180, y: 120, label: '' }, { x: 20, y: 120, label: '' }], sides: [{ from: 0, to: 1, label: '8cm' }, { from: 1, to: 2, label: '5cm' }], angles: [], type: 'rectangle' },
  },
  {
    id: 'e5-1-area-parallel',
    name: '평행사변형 넓이',
    description: '밑변 × 높이',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 50, y: 20, label: '' }, { x: 180, y: 20, label: '' }, { x: 150, y: 120, label: '' }, { x: 20, y: 120, label: '' }], sides: [{ from: 2, to: 3, label: '6cm' }], angles: [], type: 'parallelogram' },
  },
  {
    id: 'e5-1-area-tri',
    name: '삼각형 넓이',
    description: '밑변 × 높이 ÷ 2',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 80, y: 10, label: '' }, { x: 10, y: 140, label: '' }, { x: 190, y: 140, label: '' }], sides: [{ from: 1, to: 2, label: '10cm' }], angles: [] },
  },

  // ═══════════════════════════════════════
  // 5학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e5-2-sym-line',
    name: '선대칭도형',
    description: '대칭축이 있는 도형',
    schoolLevel: 'elementary',
    gradeKey: '5학년 2학기',
    chapter: '합동과 대칭',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 20, y: 150, label: 'B' }, { x: 180, y: 150, label: 'C' }], sides: [{ from: 0, to: 1, label: '5cm' }, { from: 0, to: 2, label: '5cm' }], angles: [] },
  },
  {
    id: 'e5-2-sym-point',
    name: '점대칭도형',
    description: '점 대칭 중심이 있는 도형',
    schoolLevel: 'elementary',
    gradeKey: '5학년 2학기',
    chapter: '합동과 대칭',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 50, y: 20, label: 'A' }, { x: 170, y: 20, label: 'B' }, { x: 150, y: 130, label: 'C' }, { x: 30, y: 130, label: 'D' }], sides: [], angles: [], type: 'parallelogram' },
  },
  {
    id: 'e5-2-prism-cube',
    name: '정육면체',
    description: '정육면체 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '5학년 2학기',
    chapter: '직육면체',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cube', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'e5-2-prism-rect',
    name: '직육면체',
    description: '직육면체 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '5학년 2학기',
    chapter: '직육면체',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'rectangular_prism', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'e5-2-net-cube',
    name: '정육면체 전개도',
    description: '정육면체를 펼친 모양',
    schoolLevel: 'elementary',
    gradeKey: '5학년 2학기',
    chapter: '직육면체',
    diagramType: 'net_diagram',
    defaultParams: { shape: 'cube', labels: [], foldLines: true, color: '#3B82F6' },
  },

  // ═══════════════════════════════════════
  // 6학년 1학기
  // ═══════════════════════════════════════
  {
    id: 'e6-1-prism',
    name: '각기둥 (삼각기둥)',
    description: '삼각기둥 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '각기둥과 각뿔',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'rectangular_prism', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'e6-1-pyramid',
    name: '각뿔 (사각뿔)',
    description: '사각뿔 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '각기둥과 각뿔',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'pyramid', labels: [], showHiddenEdges: true, color: '#F97316' },
  },
  {
    id: 'e6-1-net-prism',
    name: '각기둥 전개도',
    description: '삼각기둥 전개도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '각기둥과 각뿔',
    diagramType: 'net_diagram',
    defaultParams: { shape: 'rectangular_prism', labels: [], foldLines: true, color: '#3B82F6' },
  },
  {
    id: 'e6-1-net-pyramid',
    name: '각뿔 전개도',
    description: '사각뿔 전개도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '각기둥과 각뿔',
    diagramType: 'net_diagram',
    defaultParams: { shape: 'pyramid', labels: [], foldLines: true, color: '#F97316' },
  },
  {
    id: 'e6-1-graph-pic',
    name: '그림그래프',
    description: '기호가 여러 개를 나타내는 그래프',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '여러 가지 그래프',
    diagramType: 'picture_graph',
    defaultParams: { categories: ['서울', '부산', '대구', '인천'], values: [10, 7, 5, 8], symbol: '●', symbolValue: 2, title: '도시별 학생 수' },
  },
  {
    id: 'e6-1-graph-band',
    name: '띠그래프',
    description: '비율을 띠로 표현',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '여러 가지 그래프',
    diagramType: 'band_chart',
    defaultParams: { segments: [{ label: '국어', value: 30 }, { label: '수학', value: 25 }, { label: '영어', value: 25 }, { label: '기타', value: 20 }], title: '좋아하는 과목', showPercent: true },
  },
  {
    id: 'e6-1-graph-pie',
    name: '원그래프',
    description: '비율을 원으로 표현',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '여러 가지 그래프',
    diagramType: 'pie_chart',
    defaultParams: { segments: [{ label: '걷기', value: 40 }, { label: '자전거', value: 25 }, { label: '버스', value: 20 }, { label: '자동차', value: 15 }], title: '등교 방법', showPercent: true },
  },
  {
    id: 'e6-1-ratio-pie',
    name: '비율 원그래프',
    description: '비율을 원그래프로 표현',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '여러 가지 그래프',
    diagramType: 'pie_chart',
    defaultParams: { segments: [{ label: '남학생', value: 55 }, { label: '여학생', value: 45 }], title: '반 구성', showPercent: true },
  },
  {
    id: 'e6-1-vol-prism',
    name: '직육면체 부피',
    description: '가로 × 세로 × 높이',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '직육면체의 부피와 겉넓이',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'rectangular_prism', dimensions: { width: 4, depth: 3, height: 5 }, showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'e6-1-vol-cube',
    name: '정육면체 부피',
    description: '한 모서리 × 한 모서리 × 한 모서리',
    schoolLevel: 'elementary',
    gradeKey: '6학년 1학기',
    chapter: '직육면체의 부피와 겉넓이',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cube', dimensions: { width: 3, height: 3, depth: 3 }, showHiddenEdges: true, color: '#10B981' },
  },

  // ═══════════════════════════════════════
  // 6학년 2학기
  // ═══════════════════════════════════════
  {
    id: 'e6-2-stack',
    name: '쌓기나무',
    description: '쌓기나무로 만든 입체',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '공간과 입체',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cube', labels: [], showHiddenEdges: true, color: '#7C3AED' },
  },
  {
    id: 'e6-2-circle-circum',
    name: '원주 (원둘레)',
    description: '원주 = 지름 × π',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '원의 넓이',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'd', position: 'diameter' }], arcs: [] },
  },
  {
    id: 'e6-2-circle-area',
    name: '원의 넓이',
    description: '넓이 = π × r²',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '원의 넓이',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'r', position: 'radius' }], arcs: [] },
  },
  {
    id: 'e6-2-cylinder',
    name: '원기둥',
    description: '원기둥 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '원기둥, 원뿔, 구',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cylinder', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'e6-2-cone',
    name: '원뿔',
    description: '원뿔 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '원기둥, 원뿔, 구',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cone', labels: [], showHiddenEdges: true, color: '#F97316' },
  },
  {
    id: 'e6-2-sphere',
    name: '구',
    description: '구 겨냥도',
    schoolLevel: 'elementary',
    gradeKey: '6학년 2학기',
    chapter: '원기둥, 원뿔, 구',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'sphere', labels: [], showHiddenEdges: true, color: '#10B981' },
  },

  // ═══════════════════════════════════════
  // 5학년 1학기 — 다각형의 둘레와 넓이 (보충 polygon 프리셋)
  // ═══════════════════════════════════════
  {
    id: 'e5-1-polygon-staircase-2',
    name: '2단 계단',
    description: '정사각형 2개를 계단 모양으로 — 넓이/둘레',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 120 }, { x: 200, y: 120 }, { x: 200, y: 60 }, { x: 100, y: 60 }, { x: 100, y: 0 }, { x: 0, y: 0 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5],
      fill: '#A7F3D0',
    },
  },
  {
    id: 'e5-1-polygon-staircase-3',
    name: '3단 계단',
    description: '정사각형 3개 계단',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 180 }, { x: 240, y: 180 }, { x: 240, y: 120 }, { x: 160, y: 120 }, { x: 160, y: 60 }, { x: 80, y: 60 }, { x: 80, y: 0 }, { x: 0, y: 0 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5, 6, 7],
      fill: '#FDE68A',
    },
  },
  {
    id: 'e5-1-polygon-l-shape',
    name: 'L자 도형',
    description: 'L자 6각형 넓이 — 두 직사각형 분할',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 120 }, { x: 200, y: 120 }, { x: 200, y: 60 }, { x: 80, y: 60 }, { x: 80, y: 0 }, { x: 0, y: 0 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5],
      fill: '#DBEAFE',
    },
  },
  {
    id: 'e5-1-polygon-t-shape',
    name: 'T자 도형',
    description: 'T자 8각형',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 60 }, { x: 200, y: 60 }, { x: 200, y: 120 }, { x: 120, y: 120 }, { x: 120, y: 200 }, { x: 80, y: 200 }, { x: 80, y: 120 }, { x: 0, y: 120 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5, 6, 7],
      fill: '#FCE7F3',
    },
  },
  {
    id: 'e5-1-polygon-u-shape',
    name: 'ㄷ자/U자 도형',
    description: '가운데 파인 ㄷ자 모양',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 0 }, { x: 200, y: 0 }, { x: 200, y: 200 }, { x: 140, y: 200 }, { x: 140, y: 60 }, { x: 60, y: 60 }, { x: 60, y: 200 }, { x: 0, y: 200 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5, 6, 7],
      fill: '#FEF3C7',
    },
  },
  {
    id: 'e5-1-polygon-house',
    name: '집 모양 오각형',
    description: '직사각형 + 삼각형 합성 — 분리 계산 문제',
    schoolLevel: 'elementary',
    gradeKey: '5학년 1학기',
    chapter: '다각형의 둘레와 넓이',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 200 }, { x: 200, y: 200 }, { x: 200, y: 80 }, { x: 100, y: 0 }, { x: 0, y: 80 }],
      // 지붕 꼭짓점(2,3,4)은 90°가 아니므로 직각 표시하지 않음
      rightAngleMarks: [0, 1],
      fill: '#E0E0F0',
    },
  },
];
