import type { DiagramPreset } from './types';

/** 고등학교 다이어그램 프리셋 */
export const HIGH_PRESETS: DiagramPreset[] = [
  // ═══════════════════════════════════════
  // 공통수학1
  // ═══════════════════════════════════════
  {
    id: 'h-cm1-quadfunc',
    name: '이차함수 그래프',
    description: 'y = ax² + bx + c 그래프',
    schoolLevel: 'high',
    gradeKey: '공통수학1',
    chapter: '방정식과 부등식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-3, 8], gridStep: 1, functions: [{ expression: 'x^2-2*x-1', label: 'y=x²-2x-1' }], points: [{ x: 1, y: -2, label: '꼭짓점(1,-2)' }] },
  },
  {
    id: 'h-cm1-quadmax',
    name: '이차함수 최대·최소',
    description: '정의역 제한 시 최대/최소',
    schoolLevel: 'high',
    gradeKey: '공통수학1',
    chapter: '방정식과 부등식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '-x^2+4*x-1', label: 'y=-x²+4x-1' }], points: [{ x: 2, y: 3, label: '최댓값(2,3)' }] },
  },
  {
    id: 'h-cm1-quadineq',
    name: '이차부등식',
    description: 'x² - 4 ≤ 0 해의 범위',
    schoolLevel: 'high',
    gradeKey: '공통수학1',
    chapter: '방정식과 부등식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'x^2-4', label: 'y=x²-4' }], points: [{ x: -2, y: 0, label: '-2' }, { x: 2, y: 0, label: '2' }] },
  },
  {
    id: 'h-cm1-quadroots',
    name: '이차방정식의 판별식',
    description: 'D>0, D=0, D<0 그래프 비교',
    schoolLevel: 'high',
    gradeKey: '공통수학1',
    chapter: '방정식과 부등식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-2, 8], gridStep: 1, functions: [{ expression: 'x^2-4*x+3', label: 'D>0', color: '#3B82F6' }, { expression: 'x^2-4*x+4', label: 'D=0', color: '#10B981' }, { expression: 'x^2-4*x+5', label: 'D<0', color: '#EF4444' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 공통수학2
  // ═══════════════════════════════════════
  {
    id: 'h-cm2-coord-dist',
    name: '두 점 사이의 거리',
    description: '좌표평면 위 두 점 사이의 거리',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '평면좌표',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-2, 8], yRange: [-2, 8], gridStep: 1, points: [{ x: 1, y: 2, label: 'A(1,2)' }, { x: 5, y: 6, label: 'B(5,6)' }], lines: [{ points: [{ x: 1, y: 2 }, { x: 5, y: 6 }], color: '#3B82F6', style: 'dashed' }] },
  },
  {
    id: 'h-cm2-coord-div',
    name: '내분점',
    description: '선분의 내분점',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '평면좌표',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-1, 7], yRange: [-1, 7], gridStep: 1, points: [{ x: 1, y: 1, label: 'A' }, { x: 5, y: 5, label: 'B' }, { x: 3, y: 3, label: 'P(내분점)' }], lines: [{ points: [{ x: 1, y: 1 }, { x: 5, y: 5 }], color: '#3B82F6' }] },
  },
  {
    id: 'h-cm2-line-eq',
    name: '직선의 방정식',
    description: 'y = mx + n 형태',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '직선의 방정식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '2*x-1', label: 'y=2x-1' }], points: [{ x: 0, y: -1, label: 'y절편' }, { x: 0.5, y: 0, label: 'x절편' }] },
  },
  {
    id: 'h-cm2-line-parallel',
    name: '두 직선의 위치 관계',
    description: '평행과 수직',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '직선의 방정식',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '2*x+1', label: 'y=2x+1', color: '#3B82F6' }, { expression: '2*x-3', label: 'y=2x-3', color: '#EF4444' }], points: [] },
  },
  {
    id: 'h-cm2-line-dist',
    name: '점과 직선 사이의 거리',
    description: '점에서 직선까지 수선의 발',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '직선의 방정식',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-3, 7], yRange: [-2, 6], gridStep: 1, points: [{ x: 3, y: 4, label: 'P(3,4)' }], lines: [{ points: [{ x: -2, y: 0 }, { x: 6, y: 4 }], color: '#3B82F6' }] },
  },
  {
    id: 'h-cm2-circle-eq',
    name: '원의 방정식',
    description: '(x-a)² + (y-b)² = r²',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '원의 방정식',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O(a,b)', position: 'center' }, { text: 'r', position: 'radius' }], arcs: [] },
  },
  {
    id: 'h-cm2-circle-line',
    name: '원과 직선의 위치 관계',
    description: '교점 2개/접선/외부',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '원의 방정식',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, points: [{ x: 0, y: 0, label: 'O' }], lines: [{ points: [{ x: -4, y: -1 }, { x: 4, y: 3 }], color: '#EF4444' }] },
  },
  {
    id: 'h-cm2-circle-tangent',
    name: '원의 접선',
    description: '접점에서의 접선 방정식',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '원의 방정식',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'T', position: 'tangent' }], arcs: [] },
  },
  {
    id: 'h-cm2-trans-parallel',
    name: '평행이동',
    description: '(x,y) → (x+a, y+b)',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '도형의 이동',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 8], yRange: [-3, 8], gridStep: 1, points: [{ x: 1, y: 2, label: 'A' }, { x: 4, y: 5, label: "A'" }], lines: [{ points: [{ x: 1, y: 2 }, { x: 4, y: 5 }], color: '#F97316', style: 'dashed' }] },
  },
  {
    id: 'h-cm2-trans-symmetry',
    name: '대칭이동',
    description: 'x축/y축/원점 대칭',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '도형의 방정식',
    section: '도형의 이동',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, points: [{ x: 3, y: 4, label: 'P' }, { x: 3, y: -4, label: "P'(x축)" }, { x: -3, y: 4, label: "P''(y축)" }], lines: [] },
  },
  {
    id: 'h-cm2-set-venn',
    name: '벤 다이어그램',
    description: '집합의 연산',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '집합과 명제',
    diagramType: 'venn_diagram',
    defaultParams: { sets: [{ label: 'A', elements: ['1', '3', '5'] }, { label: 'B', elements: ['2', '4', '6'] }], intersection: { elements: ['3'] } },
  },
  {
    id: 'h-cm2-set-venn3',
    name: '벤 다이어그램 (3집합)',
    description: '세 집합의 관계',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '집합과 명제',
    diagramType: 'venn_diagram',
    defaultParams: { sets: [{ label: 'A', elements: [] }, { label: 'B', elements: [] }, { label: 'C', elements: [] }], intersection: { elements: [] } },
  },
  {
    id: 'h-cm2-func-rational',
    name: '유리함수',
    description: 'y = k/(x-p) + q 그래프',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '함수와 그래프',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-6, 6], yRange: [-6, 6], gridStep: 1, functions: [{ expression: '2/(x-1)+2', label: 'y=2/(x-1)+2' }], points: [] },
  },
  {
    id: 'h-cm2-func-irrational',
    name: '무리함수',
    description: 'y = √(ax+b) 그래프',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '함수와 그래프',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-2, 10], yRange: [-1, 6], gridStep: 1, functions: [{ expression: 'sqrt(x)', label: 'y=√x' }], points: [{ x: 0, y: 0, label: '시작점' }] },
  },
  {
    id: 'h-cm2-func-inverse',
    name: '역함수',
    description: 'y = f(x)와 y = f⁻¹(x)',
    schoolLevel: 'high',
    gradeKey: '공통수학2',
    chapter: '함수와 그래프',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-3, 6], yRange: [-3, 6], gridStep: 1, functions: [{ expression: '2*x+1', label: 'y=2x+1', color: '#3B82F6' }, { expression: '0.5*x-0.5', label: 'y=½x-½', color: '#EF4444' }, { expression: 'x', label: 'y=x', color: '#9CA3AF' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 대수
  // ═══════════════════════════════════════
  {
    id: 'h-alg-exp',
    name: '지수함수',
    description: 'y = 2ˣ 그래프',
    schoolLevel: 'high',
    gradeKey: '대수',
    chapter: '지수함수와 로그함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-1, 8], gridStep: 1, functions: [{ expression: '2^x', label: 'y=2ˣ' }], points: [{ x: 0, y: 1, label: '(0,1)' }] },
  },
  {
    id: 'h-alg-log',
    name: '로그함수',
    description: 'y = log₂x 그래프',
    schoolLevel: 'high',
    gradeKey: '대수',
    chapter: '지수함수와 로그함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 8], yRange: [-4, 4], gridStep: 1, functions: [{ expression: 'log(x)/log(2)', label: 'y=log₂x' }], points: [{ x: 1, y: 0, label: '(1,0)' }] },
  },
  {
    id: 'h-alg-sin',
    name: '사인함수',
    description: 'y = sin x 그래프',
    schoolLevel: 'high',
    gradeKey: '대수',
    chapter: '삼각함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-7, 7], yRange: [-2, 2], gridStep: 1, functions: [{ expression: 'sin(x)', label: 'y=sin x' }], points: [] },
  },
  {
    id: 'h-alg-cos',
    name: '코사인함수',
    description: 'y = cos x 그래프',
    schoolLevel: 'high',
    gradeKey: '대수',
    chapter: '삼각함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-7, 7], yRange: [-2, 2], gridStep: 1, functions: [{ expression: 'cos(x)', label: 'y=cos x' }], points: [] },
  },
  {
    id: 'h-alg-tan',
    name: '탄젠트함수',
    description: 'y = tan x 그래프',
    schoolLevel: 'high',
    gradeKey: '대수',
    chapter: '삼각함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'tan(x)', label: 'y=tan x' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 미적분I
  // ═══════════════════════════════════════
  {
    id: 'h-calc1-tangent',
    name: '접선의 방정식',
    description: '곡선 위 점에서의 접선',
    schoolLevel: 'high',
    gradeKey: '미적분I',
    chapter: '미분',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-3, 5], yRange: [-2, 10], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²', color: '#3B82F6' }, { expression: '4*x-4', label: '접선: y=4x-4', color: '#EF4444' }], points: [{ x: 2, y: 4, label: '접점(2,4)' }] },
  },
  {
    id: 'h-calc1-extrema',
    name: '극대·극소',
    description: '함수의 증가/감소, 극값',
    schoolLevel: 'high',
    gradeKey: '미적분I',
    chapter: '미분',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-3, 4], yRange: [-5, 8], gridStep: 1, functions: [{ expression: 'x^3-3*x', label: 'y=x³-3x' }], points: [{ x: -1, y: 2, label: '극대' }, { x: 1, y: -2, label: '극소' }] },
  },
  {
    id: 'h-calc1-graph',
    name: '함수의 그래프 개형',
    description: '3차 함수 그래프',
    schoolLevel: 'high',
    gradeKey: '미적분I',
    chapter: '미분',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-8, 8], gridStep: 1, functions: [{ expression: 'x^3-3*x^2+1', label: 'y=x³-3x²+1' }], points: [] },
  },
  {
    id: 'h-calc1-area',
    name: '정적분과 넓이',
    description: '곡선과 x축 사이 넓이',
    schoolLevel: 'high',
    gradeKey: '미적분I',
    chapter: '적분',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 4], yRange: [-1, 6], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²' }], points: [{ x: 0, y: 0, label: 'a=0' }, { x: 3, y: 9, label: 'b=3' }] },
  },
  {
    id: 'h-calc1-area2',
    name: '두 곡선 사이의 넓이',
    description: '두 함수 사이 영역',
    schoolLevel: 'high',
    gradeKey: '미적분I',
    chapter: '적분',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-2, 4], yRange: [-1, 8], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²', color: '#3B82F6' }, { expression: '2*x+3', label: 'y=2x+3', color: '#EF4444' }], points: [{ x: -1, y: 1, label: '교점' }, { x: 3, y: 9, label: '교점' }] },
  },

  // ═══════════════════════════════════════
  // 미적분II
  // ═══════════════════════════════════════
  {
    id: 'h-calc2-area',
    name: '정적분 활용 (넓이)',
    description: '초월함수의 넓이',
    schoolLevel: 'high',
    gradeKey: '미적분II',
    chapter: '적분법',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 7], yRange: [-2, 3], gridStep: 1, functions: [{ expression: 'sin(x)', label: 'y=sin x' }], points: [] },
  },
  {
    id: 'h-calc2-volume',
    name: '회전체의 부피',
    description: 'x축 회전 부피',
    schoolLevel: 'high',
    gradeKey: '미적분II',
    chapter: '적분법',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 4], yRange: [-1, 4], gridStep: 1, functions: [{ expression: 'sqrt(x)', label: 'y=√x' }], points: [{ x: 0, y: 0, label: '' }, { x: 4, y: 2, label: '' }] },
  },
  {
    id: 'h-calc2-exp-integral',
    name: '지수함수의 정적분',
    description: 'eˣ의 넓이',
    schoolLevel: 'high',
    gradeKey: '미적분II',
    chapter: '적분법',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-2, 3], yRange: [-1, 8], gridStep: 1, functions: [{ expression: 'exp(x)', label: 'y=eˣ' }], points: [{ x: 0, y: 1, label: '(0,1)' }] },
  },
  {
    id: 'h-calc2-trig-diff',
    name: '삼각함수의 미분',
    description: 'sin x와 cos x 비교',
    schoolLevel: 'high',
    gradeKey: '미적분II',
    chapter: '미분법',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-7, 7], yRange: [-2, 2], gridStep: 1, functions: [{ expression: 'sin(x)', label: 'y=sin x', color: '#3B82F6' }, { expression: 'cos(x)', label: "y=cos x (sin' x)", color: '#EF4444' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 기하
  // ═══════════════════════════════════════
  {
    id: 'h-geo-parabola',
    name: '포물선',
    description: 'y² = 4px 형태',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '이차곡선',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-1, 8], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'sqrt(4*x)', label: 'y²=4x (위)', color: '#3B82F6' }, { expression: '-sqrt(4*x)', label: 'y²=4x (아래)', color: '#3B82F6' }], points: [{ x: 1, y: 0, label: '초점F(1,0)' }] },
  },
  {
    id: 'h-geo-ellipse',
    name: '타원',
    description: 'x²/a² + y²/b² = 1',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '이차곡선',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-4, 4], gridStep: 1, points: [{ x: -2, y: 0, label: "F'" }, { x: 2, y: 0, label: 'F' }, { x: 0, y: 0, label: 'O' }], lines: [] },
  },
  {
    id: 'h-geo-hyperbola',
    name: '쌍곡선',
    description: 'x²/a² - y²/b² = 1',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '이차곡선',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-6, 6], yRange: [-5, 5], gridStep: 1, points: [{ x: -3, y: 0, label: "F'" }, { x: 3, y: 0, label: 'F' }, { x: 0, y: 0, label: 'O' }], lines: [{ points: [{ x: -6, y: -4 }, { x: 6, y: 4 }], color: '#9CA3AF', style: 'dashed' }, { points: [{ x: -6, y: 4 }, { x: 6, y: -4 }], color: '#9CA3AF', style: 'dashed' }] },
  },
  {
    id: 'h-geo-conic-tangent',
    name: '이차곡선의 접선',
    description: '이차곡선과 직선의 접선',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '이차곡선',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 6], yRange: [-3, 8], gridStep: 1, functions: [{ expression: 'x^2/4', label: 'y=x²/4', color: '#3B82F6' }, { expression: 'x-1', label: '접선', color: '#EF4444' }], points: [{ x: 2, y: 1, label: '접점' }] },
  },
  {
    id: 'h-geo-vector',
    name: '벡터의 연산',
    description: '벡터의 덧셈과 뺄셈',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '평면벡터',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-1, 7], yRange: [-1, 6], gridStep: 1, points: [{ x: 0, y: 0, label: 'O' }, { x: 3, y: 2, label: 'A' }, { x: 1, y: 4, label: 'B' }, { x: 4, y: 6, label: 'A+B' }], lines: [{ points: [{ x: 0, y: 0 }, { x: 3, y: 2 }], color: '#3B82F6' }, { points: [{ x: 0, y: 0 }, { x: 1, y: 4 }], color: '#EF4444' }, { points: [{ x: 0, y: 0 }, { x: 4, y: 6 }], color: '#10B981' }] },
  },
  {
    id: 'h-geo-dot-product',
    name: '벡터의 내적',
    description: '두 벡터의 내적과 각도',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '평면벡터',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-1, 6], yRange: [-1, 5], gridStep: 1, points: [{ x: 0, y: 0, label: 'O' }, { x: 4, y: 1, label: 'A' }, { x: 2, y: 4, label: 'B' }], lines: [{ points: [{ x: 0, y: 0 }, { x: 4, y: 1 }], color: '#3B82F6' }, { points: [{ x: 0, y: 0 }, { x: 2, y: 4 }], color: '#EF4444' }] },
  },
  {
    id: 'h-geo-space-solid',
    name: '공간도형',
    description: '직선과 평면의 위치 관계',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '공간도형과 공간좌표',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cube', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'h-geo-space-proj',
    name: '정사영',
    description: '정사영의 넓이',
    schoolLevel: 'high',
    gradeKey: '기하',
    chapter: '공간도형과 공간좌표',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'prism', labels: [], showHiddenEdges: true, color: '#7C3AED' },
  },

  // ═══════════════════════════════════════
  // 확률과 통계
  // ═══════════════════════════════════════
  {
    id: 'h-stat-normal',
    name: '정규분포 곡선',
    description: 'N(μ, σ²) 정규분포',
    schoolLevel: 'high',
    gradeKey: '확률과 통계',
    chapter: '통계',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-0.1, 0.5], gridStep: 1, functions: [{ expression: 'exp(-x^2/2)/sqrt(2*3.14159)', label: 'N(0,1)' }], points: [] },
  },
  {
    id: 'h-stat-binomial',
    name: '이항분포',
    description: 'B(n, p) 이항분포',
    schoolLevel: 'high',
    gradeKey: '확률과 통계',
    chapter: '통계',
    diagramType: 'bar_chart',
    defaultParams: { categories: ['0', '1', '2', '3', '4', '5'], values: [1, 5, 10, 10, 5, 1], title: 'B(5, 0.5)', yLabel: '확률', barColor: '#3B82F6', horizontal: false },
  },
  {
    id: 'h-stat-normal-compare',
    name: '정규분포 비교 (σ 변화)',
    description: 'σ에 따른 분포 모양 변화',
    schoolLevel: 'high',
    gradeKey: '확률과 통계',
    chapter: '통계',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-0.05, 0.5], gridStep: 1, functions: [{ expression: 'exp(-x^2/2)/sqrt(2*3.14159)', label: 'σ=1', color: '#3B82F6' }, { expression: 'exp(-x^2/8)/(2*sqrt(2*3.14159))', label: 'σ=2', color: '#EF4444' }], points: [] },
  },
  {
    id: 'h-stat-tree-cond',
    name: '조건부확률 (수형도)',
    description: '조건부확률 P(B|A)',
    schoolLevel: 'high',
    gradeKey: '확률과 통계',
    chapter: '확률',
    diagramType: 'tree_diagram',
    defaultParams: { root: { label: '전체', children: [{ label: 'A', probability: 'P(A)', children: [{ label: 'B', probability: 'P(B|A)' }, { label: 'Bᶜ', probability: 'P(Bᶜ|A)' }] }, { label: 'Aᶜ', probability: 'P(Aᶜ)', children: [{ label: 'B', probability: 'P(B|Aᶜ)' }, { label: 'Bᶜ', probability: 'P(Bᶜ|Aᶜ)' }] }] }, title: '조건부확률', orientation: 'horizontal' },
  },
];
