import type { DiagramPreset } from './types';

/** 중학교 다이어그램 프리셋 (1~3학년) */
export const MIDDLE_PRESETS: DiagramPreset[] = [
  // ═══════════════════════════════════════
  // 1학년 1학기
  // ═══════════════════════════════════════

  // ── 소인수分해 (최대공약수/최소공배수) ──
  {
    id: 'm1-1-gcd-brick-box',
    name: '직육면체 벽돌 쌓기 (최대공약수)',
    description: '직육면체 상자를 같은 크기의 정육면체 벽돌로 빈틈없이 채우기 — 한 변은 세 변의 최대공약수',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '소인수분해',
    diagramType: 'solid_figure',
    defaultParams: {
      shape: 'rectangular_prism',
      dimensions: { width: 120, height: 90, depth: 60 },
      showHiddenEdges: true,
      color: '#EC4899',
      gridDivisions: { w: 4, h: 3, d: 2 },
    },
  },
  {
    id: 'm1-1-lcm-cube-build',
    name: '정육면체 만들기 (최소공배수)',
    description: '직육면체 벽돌을 쌓아 가장 작은 정육면체 만들기 — 한 변은 세 변의 최소공배수',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '소인수분해',
    diagramType: 'solid_figure',
    defaultParams: {
      shape: 'cube',
      showHiddenEdges: true,
      color: '#10B981',
      gridDivisions: { w: 5, h: 3, d: 4 },
    },
  },

  // ── 정수와 유리수 ──
  {
    id: 'm1-1-dice-faces',
    name: '주사위 (면에 숫자)',
    description: '보이는 3면에 숫자/분수를 표시한 주사위',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정수와 유리수',
    diagramType: 'solid_figure',
    defaultParams: {
      shape: 'cube', showHiddenEdges: false, color: '#F9A8D4',
      faceLabels: [
        { face: 'front', text: '\\frac{2}{3}' },
        { face: 'top', text: '-9' },
        { face: 'right', text: '1' },
      ],
    },
  },
  {
    id: 'm1-1-num-pyramid-3',
    name: '숫자 피라미드 (3단)',
    description: '3단 삼각형 배열 — 각 칸은 아래 두 수의 합',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정수와 유리수',
    diagramType: 'flow_chart',
    defaultParams: {
      nodes: [
        { id: 'a', text: '?', x: 80, y: 0, shape: 'circle', size: 20, color: '#FEF3C7' },
        { id: 'b', text: '3', x: 40, y: 50, shape: 'circle', size: 20 },
        { id: 'c', text: '5', x: 120, y: 50, shape: 'circle', size: 20 },
        { id: 'd', text: '-2', x: 0, y: 100, shape: 'circle', size: 20 },
        { id: 'e', text: '5', x: 80, y: 100, shape: 'circle', size: 20 },
        { id: 'f', text: '0', x: 160, y: 100, shape: 'circle', size: 20 },
      ],
      arrows: [
        { from: 'b', to: 'a', noArrowHead: true },
        { from: 'c', to: 'a', noArrowHead: true },
        { from: 'd', to: 'b', noArrowHead: true },
        { from: 'e', to: 'b', noArrowHead: true },
        { from: 'e', to: 'c', noArrowHead: true },
        { from: 'f', to: 'c', noArrowHead: true },
      ],
    },
  },
  {
    id: 'm1-1-num-pyramid-4',
    name: '숫자 피라미드 (4단)',
    description: '4단 삼각형 배열 — 한 변에 놓인 수의 합이 같음',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정수와 유리수',
    diagramType: 'flow_chart',
    defaultParams: {
      nodes: [
        { id: 'a', text: 'A', x: 120, y: 0, shape: 'circle', size: 20, color: '#FEF3C7' },
        { id: 'b', text: '8', x: 70, y: 45, shape: 'circle', size: 20 },
        { id: 'c', text: '-4', x: 170, y: 45, shape: 'circle', size: 20 },
        { id: 'd', text: 'B', x: 20, y: 90, shape: 'circle', size: 20, color: '#FEF3C7' },
        { id: 'e', text: '', x: 120, y: 90, shape: 'circle', size: 20 },
        { id: 'f', text: '6', x: 220, y: 90, shape: 'circle', size: 20 },
        { id: 'g', text: '-5', x: 0, y: 135, shape: 'circle', size: 20 },
        { id: 'h', text: '10', x: 80, y: 135, shape: 'circle', size: 20 },
        { id: 'i', text: '-7', x: 160, y: 135, shape: 'circle', size: 20 },
        { id: 'j', text: '9', x: 240, y: 135, shape: 'circle', size: 20 },
      ],
      arrows: [
        { from: 'b', to: 'a', noArrowHead: true },
        { from: 'c', to: 'a', noArrowHead: true },
        { from: 'd', to: 'b', noArrowHead: true },
        { from: 'e', to: 'b', noArrowHead: true },
        { from: 'e', to: 'c', noArrowHead: true },
        { from: 'f', to: 'c', noArrowHead: true },
        { from: 'g', to: 'd', noArrowHead: true },
        { from: 'h', to: 'd', noArrowHead: true },
        { from: 'h', to: 'e', noArrowHead: true },
        { from: 'i', to: 'e', noArrowHead: true },
        { from: 'i', to: 'f', noArrowHead: true },
        { from: 'j', to: 'f', noArrowHead: true },
      ],
    },
  },
  {
    id: 'm1-1-int-numline',
    name: '정수 수직선',
    description: '양수·음수를 수직선에 표시',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정수와 유리수',
    diagramType: 'number_line',
    defaultParams: { min: -5, max: 5, step: 1, marks: [{ value: -3, label: '-3', color: '#EF4444', showDot: true }, { value: 2, label: '+2', color: '#3B82F6', showDot: true }], showAllTickLabels: true },
  },
  {
    id: 'm1-1-numline-points',
    name: '수직선 위의 점',
    description: '수직선 위 점에 문자 표시 (라벨 위/아래 토글, 좌우 화살표 토글)',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정수와 유리수',
    diagramType: 'number_line',
    defaultParams: { min: -3, max: 3, step: 1, showAllTickLabels: true, arrowLeft: true, arrowRight: true, marks: [{ value: -2, label: 'A', color: '#333', showDot: true }, { value: -1, label: 'B', color: '#333', showDot: true }, { value: 0, label: 'C', color: '#333', showDot: true }, { value: 1, label: 'D', color: '#333', showDot: true }, { value: 2, label: 'E', color: '#333', showDot: true }] },
  },

  // ── 문자의 사용과 식 ──
  {
    id: 'm1-1-expr-rect-area',
    name: '직사각형 넓이 (변수)',
    description: '가로 a, 세로 b인 직사각형으로 식의 값 구하기',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 10, y: 10, label: 'A' }, { x: 160, y: 10, label: 'B' }, { x: 160, y: 110, label: 'C' }, { x: 10, y: 110, label: 'D' }], sides: [{ from: 0, to: 1, label: 'a' }, { from: 1, to: 2, label: 'b' }], type: 'rectangle', rightAngleMarks: [0] },
  },
  {
    id: 'm1-1-expr-l-shape',
    name: 'L자형 도형 (넓이)',
    description: 'L자형 복합 도형 넓이를 문자식으로 표현',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'fraction_rect',
    defaultParams: { rows: 3, cols: 2, coloredCells: [0, 1, 2, 3, 4], count: 1, color: '#3B82F6' },
  },
  {
    id: 'm1-1-expr-cutout',
    name: '직사각형 빼기 도형',
    description: '직사각형에서 정사각형 빼기 — 색칠 영역이 남은 부분',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'fraction_rect',
    defaultParams: { rows: 2, cols: 6, coloredCells: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], count: 1, color: '#3B82F6' },
  },
  {
    id: 'm1-1-expr-staircase',
    name: '계단형 도형 (둘레)',
    description: '계단 모양 도형의 둘레 길이를 문자식으로 표현',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'fraction_rect',
    defaultParams: { rows: 3, cols: 3, coloredCells: [0, 3, 4, 6, 7, 8], count: 1, color: '#10B981' },
  },
  {
    id: 'm1-1-expr-poster-grid',
    name: '포스터 배치 (격자)',
    description: '벽에 포스터를 격자로 배치한 모양',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'fraction_rect',
    defaultParams: { rows: 2, cols: 4, coloredCount: 8, count: 1, color: '#F97316' },
  },
  {
    id: 'm1-1-expr-flowchart',
    name: '징검다리 판별 (흐름도)',
    description: '일차식 예/아니요 분기 징검다리',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자의 사용과 식',
    diagramType: 'flow_chart',
    defaultParams: { nodes: [{ id: 'n0', text: '2x+1' }, { id: 'n1', text: '일차식?' }, { id: 'n2', text: '예 →' }, { id: 'n3', text: '아니요 ↓' }], arrows: [{ from: 'n0', to: 'n1' }, { from: 'n1', to: 'n2', label: '예' }, { from: 'n1', to: 'n3', label: '아니요' }] },
  },

  // ── 일차방정식 ──
  {
    id: 'm1-1-eq-trapezoid',
    name: '사다리꼴 넓이 활용',
    description: '사다리꼴의 윗변/아랫변/높이로 일차방정식 세우기',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '일차방정식',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 40, y: 10, label: 'A' }, { x: 140, y: 10, label: 'B' }, { x: 170, y: 110, label: 'C' }, { x: 10, y: 110, label: 'D' }], sides: [{ from: 0, to: 1, label: 'x' }, { from: 2, to: 3, label: 'x+2' }], type: 'trapezoid' },
  },

  // ── 좌표와 그래프 ──
  {
    id: 'm1-1-coord-basic',
    name: '좌표평면 (순서쌍)',
    description: '점을 좌표평면에 나타내기',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '좌표와 그래프',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, points: [{ x: 2, y: 3, label: 'A(2,3)' }, { x: -3, y: 1, label: 'B(-3,1)' }], lines: [] },
  },
  {
    id: 'm1-1-coord-graph',
    name: '좌표평면 (그래프)',
    description: '점들을 이어 그래프로 나타내기',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '좌표와 그래프',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, points: [{ x: -2, y: -1 }, { x: 0, y: 1 }, { x: 2, y: 3 }], lines: [{ points: [{ x: -2, y: -1 }, { x: 2, y: 3 }], color: '#3B82F6' }] },
  },
  {
    id: 'm1-1-coord-quadrant',
    name: '사분면',
    description: '4개 사분면 구분',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '좌표와 그래프',
    diagramType: 'coordinate_plane',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, points: [{ x: 3, y: 4, label: '제1사분면' }, { x: -3, y: 2, label: '제2사분면' }, { x: -2, y: -3, label: '제3사분면' }, { x: 4, y: -2, label: '제4사분면' }], lines: [] },
  },

  // ── 정비례와 반비례 ──
  {
    id: 'm1-1-prop-direct',
    name: '정비례 그래프',
    description: 'y = 2x 그래프',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정비례와 반비례',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '2*x', label: 'y=2x' }], points: [] },
  },
  {
    id: 'm1-1-prop-inverse',
    name: '반비례 그래프',
    description: 'y = 6/x 그래프',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정비례와 반비례',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-8, 8], yRange: [-8, 8], gridStep: 1, functions: [{ expression: '6/x', label: 'y=6/x' }], points: [] },
  },
  {
    id: 'm1-1-prop-neg',
    name: '정비례 (음수 기울기)',
    description: 'y = -x 그래프',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정비례와 반비례',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '-x', label: 'y=-x' }], points: [] },
  },
  {
    id: 'm1-1-prop-compare',
    name: '정비례 vs 반비례',
    description: 'y=2x와 y=6/x 비교',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '정비례와 반비례',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-6, 6], yRange: [-6, 6], gridStep: 1, functions: [{ expression: '2*x', label: 'y=2x (정비례)', color: '#3B82F6' }, { expression: '6/x', label: 'y=6/x (반비례)', color: '#EF4444' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 1학년 2학기
  // ═══════════════════════════════════════

  // ── 기본 도형 ──
  {
    id: 'm1-2-basic-angle',
    name: '맞꼭지각',
    description: '두 직선이 만들 때 맞꼭지각',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '기본 도형',
    diagramType: 'angle_figure',
    defaultParams: {
      angle: 50, ray1Angle: 0, label: '50°', color: '#3B82F6', showProtractor: false,
      additionalAngles: [
        { angle: 130, label: '130°', color: '#F97316' },
        { angle: 50, label: '50°', color: '#3B82F6' },
        { angle: 130, label: '', showArc: false },
      ],
    },
  },
  {
    id: 'm1-2-basic-parallel',
    name: '평행선과 동위각',
    description: '평행선에서의 동위각/엇각',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '기본 도형',
    diagramType: 'angle_figure',
    defaultParams: {
      angle: 55, ray1Angle: 0, label: '', color: '#3B82F6', showProtractor: false,
      parallelLines: [{ transversalAngle: 55, spacing: 60 }],
    },
  },
  {
    id: 'm1-2-basic-perpendicular',
    name: '수직과 수선',
    description: '두 직선이 수직으로 만남',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '기본 도형',
    diagramType: 'angle_figure',
    defaultParams: {
      angle: 90, ray1Angle: 0, label: '', color: '#3B82F6', showProtractor: false,
      additionalAngles: [
        { angle: 90, label: '', showArc: false },
        { angle: 90, label: '', showArc: false },
      ],
    },
  },

  // ── 작도와 합동 ──
  {
    id: 'm1-2-constr-sss',
    name: '삼각형 작도 (SSS)',
    description: '세 변으로 삼각형 작도',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '작도와 합동',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 140, label: 'A' }, { x: 190, y: 140, label: 'B' }, { x: 80, y: 20, label: 'C' }], sides: [{ from: 0, to: 1, label: '6cm' }, { from: 1, to: 2, label: '5cm' }, { from: 0, to: 2, label: '4cm' }], angles: [] },
  },
  {
    id: 'm1-2-constr-sas',
    name: '삼각형 합동 (SAS)',
    description: '두 변과 끼인각',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '작도와 합동',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 140, label: 'A' }, { x: 190, y: 140, label: 'B' }, { x: 100, y: 20, label: 'C' }], sides: [{ from: 0, to: 1, label: '7cm' }, { from: 0, to: 2, label: '5cm' }], angles: [{ vertex: 0, value: '60°' }] },
  },
  {
    id: 'm1-2-constr-asa',
    name: '삼각형 합동 (ASA)',
    description: '한 변과 양 끝각',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '작도와 합동',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 140, label: 'A' }, { x: 190, y: 140, label: 'B' }, { x: 100, y: 20, label: 'C' }], sides: [{ from: 0, to: 1, label: '8cm' }], angles: [{ vertex: 0, value: '50°' }, { vertex: 1, value: '70°' }] },
  },
  {
    id: 'm1-2-perp-bisector',
    name: '수직이등분선 작도',
    description: '변의 수직이등분선',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '작도와 합동',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 20, y: 150, label: 'B' }, { x: 180, y: 150, label: 'C' }], sides: [{ from: 1, to: 2, label: '' }], angles: [], auxiliaryLines: ['perpendicular_bisectors'] },
  },

  // ── 평면도형 ──
  {
    id: 'm1-2-plane-polygon',
    name: '다각형 (내각의 합)',
    description: '정육각형 내각의 합',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '평면도형',
    diagramType: 'regular_polygon',
    defaultParams: { sides: 6, diagonals: true, sideLength: '' },
  },
  {
    id: 'm1-2-plane-circle',
    name: '원과 부채꼴',
    description: '부채꼴의 호와 중심각',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '평면도형',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }], arcs: [{ startAngle: 0, endAngle: 120, label: '120°' }] },
  },
  {
    id: 'm1-2-plane-sector',
    name: '부채꼴 넓이',
    description: '부채꼴의 넓이와 호의 길이',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '평면도형',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'r', position: 'radius' }], arcs: [{ startAngle: 0, endAngle: 90, label: '90°' }] },
  },

  // ── 입체도형 ──
  {
    id: 'm1-2-solid-poly',
    name: '다면체 (정다면체)',
    description: '정육면체',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '입체도형',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cube', labels: [], showHiddenEdges: true, color: '#3B82F6' },
  },
  {
    id: 'm1-2-solid-rev',
    name: '회전체 (원기둥)',
    description: '직사각형 회전 → 원기둥',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '입체도형',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cylinder', labels: [], showHiddenEdges: true, color: '#F97316' },
  },
  {
    id: 'm1-2-solid-cone',
    name: '회전체 (원뿔)',
    description: '직각삼각형 회전 → 원뿔',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '입체도형',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'cone', labels: [], showHiddenEdges: true, color: '#10B981' },
  },
  {
    id: 'm1-2-solid-sphere',
    name: '회전체 (구)',
    description: '반원 회전 → 구',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '입체도형',
    diagramType: 'solid_figure',
    defaultParams: { shape: 'sphere', labels: [], showHiddenEdges: true, color: '#7C3AED' },
  },

  // ── 자료의 정리와 해석 ──
  {
    id: 'm1-2-data-stem',
    name: '줄기와 잎 그림',
    description: '줄기와 잎 그림으로 자료 정리',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '자료의 정리와 해석',
    diagramType: 'stem_leaf',
    defaultParams: { stems: [{ stem: 4, leaves: [2, 5, 7] }, { stem: 5, leaves: [0, 3, 6, 8] }, { stem: 6, leaves: [1, 4, 7] }, { stem: 7, leaves: [2, 5] }], title: '시험 점수' },
  },
  {
    id: 'm1-2-data-hist',
    name: '히스토그램',
    description: '도수분포표를 히스토그램으로',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '자료의 정리와 해석',
    diagramType: 'histogram',
    defaultParams: { bins: [{ range: [40, 50], frequency: 3 }, { range: [50, 60], frequency: 5 }, { range: [60, 70], frequency: 8 }, { range: [70, 80], frequency: 6 }, { range: [80, 90], frequency: 4 }, { range: [90, 100], frequency: 2 }], title: '수학 성적 분포', xLabel: '점수', yLabel: '학생 수', showFrequencyPolygon: false, color: '#3B82F6' },
  },
  {
    id: 'm1-2-data-freq',
    name: '도수분포다각형',
    description: '히스토그램 + 도수분포다각형',
    schoolLevel: 'middle',
    gradeKey: '1학년 2학기',
    chapter: '자료의 정리와 해석',
    diagramType: 'histogram',
    defaultParams: { bins: [{ range: [40, 50], frequency: 2 }, { range: [50, 60], frequency: 5 }, { range: [60, 70], frequency: 9 }, { range: [70, 80], frequency: 7 }, { range: [80, 90], frequency: 3 }], title: '', xLabel: '점수', yLabel: '도수', showFrequencyPolygon: true, color: '#10B981' },
  },

  // ═══════════════════════════════════════
  // 2학년 1학기
  // ═══════════════════════════════════════

  // ── 일차부등식 ──
  {
    id: 'm2-1-ineq-numline',
    name: '일차부등식 (수직선)',
    description: '부등식의 해를 수직선에 표시',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차부등식',
    diagramType: 'number_line',
    defaultParams: { min: -5, max: 5, step: 1, marks: [{ value: 3, label: 'x=3', color: '#EF4444' }], highlights: [{ from: -5, to: 3, color: '#3B82F6' }] },
  },
  {
    id: 'm2-1-ineq-compound',
    name: '복합부등식 수직선',
    description: '-1 ≤ x < 3 범위 표시',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차부등식',
    diagramType: 'number_line',
    defaultParams: { min: -4, max: 5, step: 1, highlights: [{ from: -1, to: 3, color: '#3B82F6', label: '' }], closedEndpoints: [-1], openEndpoints: [3] },
  },

  // ── 일차함수 ──
  {
    id: 'm2-1-linear-basic',
    name: '일차함수 (기본)',
    description: 'y = 2x + 1 그래프',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '2*x+1', label: 'y=2x+1' }], points: [] },
  },
  {
    id: 'm2-1-linear-slope',
    name: '기울기와 y절편',
    description: '기울기에 따른 그래프 변화',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'x+2', label: 'y=x+2', color: '#3B82F6' }, { expression: '2*x+2', label: 'y=2x+2', color: '#EF4444' }, { expression: '0.5*x+2', label: 'y=½x+2', color: '#10B981' }], points: [] },
  },
  {
    id: 'm2-1-linear-eq',
    name: '연립방정식의 해 (교점)',
    description: '두 일차함수의 교점',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'x+1', label: 'y=x+1', color: '#3B82F6' }, { expression: '-x+3', label: 'y=-x+3', color: '#EF4444' }], points: [{ x: 1, y: 2, label: '교점(1,2)' }] },
  },
  {
    id: 'm2-1-linear-xint',
    name: 'x절편과 y절편',
    description: '일차함수의 x절편, y절편',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '2*x-4', label: 'y=2x-4' }], points: [{ x: 0, y: -4, label: 'y절편(0,-4)' }, { x: 2, y: 0, label: 'x절편(2,0)' }] },
  },
  {
    id: 'm2-1-linear-parallel2',
    name: '평행한 두 일차함수',
    description: '기울기가 같은 두 직선',
    schoolLevel: 'middle',
    gradeKey: '2학년 1학기',
    chapter: '일차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-5, 5], gridStep: 1, functions: [{ expression: '0.5*x+2', label: 'y=½x+2', color: '#3B82F6' }, { expression: '0.5*x-1', label: 'y=½x-1', color: '#EF4444' }], points: [] },
  },

  // ═══════════════════════════════════════
  // 2학년 2학기
  // ═══════════════════════════════════════

  // ── 삼각형의 성질 ──
  {
    id: 'm2-2-tri-isosceles',
    name: '이등변삼각형의 성질',
    description: '두 밑각이 같음',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '삼각형의 성질',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 20, y: 150, label: 'B' }, { x: 180, y: 150, label: 'C' }], sides: [{ from: 0, to: 1, label: '5cm' }, { from: 0, to: 2, label: '5cm' }], angles: [{ vertex: 1, value: 'α' }, { vertex: 2, value: 'α' }] },
  },
  {
    id: 'm2-2-tri-right',
    name: '직각삼각형의 합동',
    description: 'RHA, RHS 합동',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '삼각형의 성질',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 150, label: 'A' }, { x: 190, y: 150, label: 'B' }, { x: 10, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '5cm' }], angles: [{ vertex: 0, value: '90°' }] },
  },
  {
    id: 'm2-2-tri-circum',
    name: '외심',
    description: '삼각형의 외심 (수직이등분선 교점)',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '삼각형의 성질',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 20, y: 150, label: 'B' }, { x: 180, y: 150, label: 'C' }], sides: [], angles: [], specialPoints: ['circumcenter'], auxiliaryLines: ['perpendicular_bisectors'], circumscribedCircle: true },
  },
  {
    id: 'm2-2-tri-incenter',
    name: '내심',
    description: '삼각형의 내심 (각의 이등분선 교점)',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '삼각형의 성질',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [], angles: [], specialPoints: ['incenter'], auxiliaryLines: ['angle_bisectors'], inscribedCircle: true },
  },
  {
    id: 'm2-2-angle-bisector',
    name: '각의 이등분선',
    description: '삼각형 각의 이등분선',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '삼각형의 성질',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [], angles: [], auxiliaryLines: ['angle_bisectors'] },
  },

  // ── 사각형의 성질 ──
  {
    id: 'm2-2-quad-parallel',
    name: '평행사변형',
    description: '대변이 평행하고 같음',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '사각형의 성질',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 50, y: 20, label: 'A' }, { x: 170, y: 20, label: 'B' }, { x: 150, y: 130, label: 'C' }, { x: 30, y: 130, label: 'D' }], sides: [{ from: 0, to: 1, label: 'a' }, { from: 3, to: 2, label: 'a' }], angles: [], type: 'parallelogram' },
  },
  {
    id: 'm2-2-quad-types',
    name: '여러 가지 사각형 관계',
    description: '직사각형·마름모·정사각형',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '사각형의 성질',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 180, y: 75, label: 'B' }, { x: 100, y: 140, label: 'C' }, { x: 20, y: 75, label: 'D' }], sides: [{ from: 0, to: 1, label: 'a' }, { from: 1, to: 2, label: 'a' }], angles: [], type: 'rhombus' },
  },
  {
    id: 'm2-2-quad-square',
    name: '정사각형',
    description: '네 변이 같고 네 각이 직각',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '사각형의 성질',
    diagramType: 'quadrilateral',
    defaultParams: { vertices: [{ x: 20, y: 20, label: 'A' }, { x: 140, y: 20, label: 'B' }, { x: 140, y: 140, label: 'C' }, { x: 20, y: 140, label: 'D' }], sides: [{ from: 0, to: 1, label: 'a' }], angles: [], type: 'square' },
  },

  // ── 도형의 닮음 ──
  {
    id: 'm2-2-similar',
    name: '닮음 (AA 닮음)',
    description: '두 각이 같은 삼각형',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '도형의 닮음',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [], angles: [{ vertex: 1, value: '50°' }, { vertex: 2, value: '60°' }] },
  },
  {
    id: 'm2-2-similar-ratio',
    name: '평행선과 선분의 비',
    description: '평행선 사이의 선분 비례',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '도형의 닮음',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [{ from: 0, to: 1, label: '6' }, { from: 0, to: 2, label: '8' }], angles: [] },
  },
  {
    id: 'm2-2-centroid',
    name: '삼각형의 무게중심',
    description: '세 중선의 교점',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '도형의 닮음',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [], angles: [], specialPoints: ['centroid'], auxiliaryLines: ['medians'] },
  },

  // ── 피타고라스 정리 ──
  {
    id: 'm2-2-pytha',
    name: '피타고라스 정리',
    description: 'a² + b² = c² (직각삼각형)',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '피타고라스 정리',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 140, label: 'A' }, { x: 190, y: 140, label: 'B' }, { x: 10, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '5' }, { from: 0, to: 2, label: '3' }, { from: 1, to: 2, label: '4' }], angles: [{ vertex: 0, value: '90°' }] },
  },
  {
    id: 'm2-2-pytha-app',
    name: '피타고라스 정리 활용',
    description: '실생활 적용 문제',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '피타고라스 정리',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 150, label: 'A' }, { x: 190, y: 150, label: 'B' }, { x: 10, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '?' }, { from: 0, to: 2, label: '8' }, { from: 1, to: 2, label: '10' }], angles: [{ vertex: 0, value: '90°' }] },
  },

  // ── 확률 ──
  {
    id: 'm2-2-prob-tree',
    name: '경우의 수 (수형도)',
    description: '확률의 수형도',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '확률',
    diagramType: 'tree_diagram',
    defaultParams: { root: { label: '시작', children: [{ label: '앞', probability: '1/2', children: [{ label: '앞', probability: '1/2' }, { label: '뒤', probability: '1/2' }] }, { label: '뒤', probability: '1/2', children: [{ label: '앞', probability: '1/2' }, { label: '뒤', probability: '1/2' }] }] }, title: '동전 2번 던지기', orientation: 'horizontal' },
  },
  {
    id: 'm2-2-prob-tree2',
    name: '확률 계산 (수형도)',
    description: '구슬 뽑기 확률',
    schoolLevel: 'middle',
    gradeKey: '2학년 2학기',
    chapter: '확률',
    diagramType: 'tree_diagram',
    defaultParams: { root: { label: '주머니', children: [{ label: '빨강', probability: '3/5', children: [{ label: '빨강' }, { label: '파랑' }] }, { label: '파랑', probability: '2/5', children: [{ label: '빨강' }, { label: '파랑' }] }] }, title: '', orientation: 'horizontal' },
  },

  // ═══════════════════════════════════════
  // 3학년 1학기
  // ═══════════════════════════════════════

  // ── 실수와 그 연산 ──
  {
    id: 'm3-1-real-numline',
    name: '무리수 수직선',
    description: '√2, √3 위치 표시',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '실수와 그 연산',
    diagramType: 'number_line',
    defaultParams: { min: 0, max: 3, step: 0.5, marks: [{ value: 1, label: '1', showDot: true }, { value: 1.414, label: '√2', color: '#EF4444', showDot: true }, { value: 1.732, label: '√3', color: '#3B82F6', showDot: true }, { value: 2, label: '2', showDot: true }], showAllTickLabels: true },
  },

  // ── 이차함수 ──
  {
    id: 'm3-1-quad-basic',
    name: '이차함수 (기본형)',
    description: 'y = x² 그래프',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-5, 5], yRange: [-2, 10], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²' }], points: [{ x: 0, y: 0, label: '꼭짓점' }] },
  },
  {
    id: 'm3-1-quad-vertex',
    name: '이차함수 (꼭짓점)',
    description: 'y = (x-1)² + 2 그래프',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-3, 5], yRange: [-1, 10], gridStep: 1, functions: [{ expression: '(x-1)^2+2', label: 'y=(x-1)²+2' }], points: [{ x: 1, y: 2, label: '꼭짓점(1,2)' }] },
  },
  {
    id: 'm3-1-quad-compare',
    name: '이차함수 비교',
    description: 'a값에 따른 그래프 변화',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-2, 8], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²', color: '#3B82F6' }, { expression: '2*x^2', label: 'y=2x²', color: '#EF4444' }, { expression: '0.5*x^2', label: 'y=½x²', color: '#10B981' }], points: [] },
  },
  {
    id: 'm3-1-quad-down',
    name: '이차함수 (아래로 볼록)',
    description: 'y = -x² + 4 그래프',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-2, 6], gridStep: 1, functions: [{ expression: '-x^2+4', label: 'y=-x²+4' }], points: [{ x: 0, y: 4, label: '꼭짓점(0,4)' }] },
  },
  {
    id: 'm3-1-quad-axis',
    name: '이차함수 (축의 방정식)',
    description: 'y = (x-2)² 대칭축 x=2',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-2, 6], yRange: [-1, 8], gridStep: 1, functions: [{ expression: '(x-2)^2', label: 'y=(x-2)²' }], points: [{ x: 2, y: 0, label: '꼭짓점(2,0)' }] },
  },
  {
    id: 'm3-1-quad-roots',
    name: '이차함수와 x축 교점',
    description: 'y = x² - 4 (x절편: ±2)',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 4], yRange: [-5, 5], gridStep: 1, functions: [{ expression: 'x^2-4', label: 'y=x²-4' }], points: [{ x: -2, y: 0, label: '(-2,0)' }, { x: 2, y: 0, label: '(2,0)' }] },
  },
  {
    id: 'm3-1-quad-shift',
    name: '이차함수 평행이동',
    description: 'y=x², y=(x-2)², y=x²+3 비교',
    schoolLevel: 'middle',
    gradeKey: '3학년 1학기',
    chapter: '이차함수',
    diagramType: 'function_graph',
    defaultParams: { xRange: [-4, 6], yRange: [-2, 10], gridStep: 1, functions: [{ expression: 'x^2', label: 'y=x²', color: '#9CA3AF' }, { expression: '(x-2)^2', label: 'y=(x-2)²', color: '#3B82F6' }, { expression: 'x^2+3', label: 'y=x²+3', color: '#EF4444' }], points: [{ x: 0, y: 0, label: 'O' }, { x: 2, y: 0, label: '' }, { x: 0, y: 3, label: '' }] },
  },

  // ═══════════════════════════════════════
  // 3학년 2학기
  // ═══════════════════════════════════════

  // ── 삼각비 ──
  {
    id: 'm3-2-trig-basic',
    name: '삼각비 (기본)',
    description: 'sin, cos, tan 정의',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '삼각비',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 140, label: 'A' }, { x: 190, y: 140, label: 'B' }, { x: 190, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '밑변' }, { from: 1, to: 2, label: '높이' }, { from: 0, to: 2, label: '빗변' }], angles: [{ vertex: 1, value: '90°' }, { vertex: 0, value: 'θ' }] },
  },
  {
    id: 'm3-2-trig-special',
    name: '특수각 삼각비 (30°, 45°, 60°)',
    description: '30°-60°-90° 삼각형',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '삼각비',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 150, label: 'A' }, { x: 160, y: 150, label: 'B' }, { x: 160, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '√3' }, { from: 1, to: 2, label: '1' }, { from: 0, to: 2, label: '2' }], angles: [{ vertex: 1, value: '90°' }, { vertex: 0, value: '30°' }, { vertex: 2, value: '60°' }] },
  },
  {
    id: 'm3-2-trig-app',
    name: '삼각비 활용',
    description: '건물 높이 구하기',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '삼각비',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 10, y: 150, label: 'A' }, { x: 190, y: 150, label: 'B' }, { x: 190, y: 10, label: 'C' }], sides: [{ from: 0, to: 1, label: '20m' }, { from: 1, to: 2, label: 'h' }], angles: [{ vertex: 1, value: '90°' }, { vertex: 0, value: '35°' }] },
  },
  {
    id: 'm3-2-trig-unit',
    name: '단위원 삼각비',
    description: '반지름 1인 원에서 sinθ, cosθ',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '삼각비',
    diagramType: 'circle',
    defaultParams: { radius: 70, labels: [{ text: 'O', position: 'center' }, { text: '1', position: 'radius' }], arcs: [{ startAngle: 0, endAngle: 60, label: '60°' }] },
  },
  {
    id: 'm3-2-law-sines',
    name: '사인법칙',
    description: 'a/sinA = b/sinB = c/sinC',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '삼각비',
    diagramType: 'triangle',
    defaultParams: { vertices: [{ x: 100, y: 10, label: 'A' }, { x: 10, y: 150, label: 'B' }, { x: 190, y: 150, label: 'C' }], sides: [{ from: 0, to: 1, label: 'b' }, { from: 1, to: 2, label: 'a' }, { from: 0, to: 2, label: 'c' }], angles: [{ vertex: 0, value: 'A' }, { vertex: 1, value: 'B' }, { vertex: 2, value: 'C' }] },
  },

  // ── 원의 성질 ──
  {
    id: 'm3-2-circle-chord',
    name: '원과 현',
    description: '현의 수직이등분선은 중심을 지남',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '원의 성질',
    diagramType: 'circle',
    defaultParams: { radius: 70, labels: [{ text: 'O', position: 'center' }], arcs: [] },
  },
  {
    id: 'm3-2-circle-tangent',
    name: '원과 접선',
    description: '접선은 접점에서 반지름에 수직',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '원의 성질',
    diagramType: 'circle',
    defaultParams: { radius: 60, labels: [{ text: 'O', position: 'center' }, { text: 'T', position: 'tangent' }], arcs: [] },
  },
  {
    id: 'm3-2-circle-inscribed',
    name: '원주각',
    description: '원주각 = 중심각의 1/2',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '원의 성질',
    diagramType: 'circle',
    defaultParams: { radius: 70, labels: [{ text: 'O', position: 'center' }], arcs: [{ startAngle: 0, endAngle: 120, label: '120°' }] },
  },
  {
    id: 'm3-2-circle-central',
    name: '중심각과 호',
    description: '같은 호에 대한 원주각',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '원의 성질',
    diagramType: 'circle',
    defaultParams: { radius: 70, labels: [{ text: 'O', position: 'center' }], arcs: [{ startAngle: 30, endAngle: 150, label: '' }] },
  },
  {
    id: 'm3-2-circle-chord-perp',
    name: '현의 수직이등분선',
    description: '현의 수직이등분선은 중심을 지남',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '원의 성질',
    diagramType: 'circle',
    defaultParams: { radius: 70, labels: [{ text: 'O', position: 'center' }, { text: 'M', position: 'chord_midpoint' }], arcs: [] },
  },

  // ── 통계 ──
  {
    id: 'm3-2-stat-scatter',
    name: '산점도 (양의 상관)',
    description: '양의 상관관계 산점도',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '통계',
    diagramType: 'scatter_plot',
    defaultParams: { points: [{ x: 1, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 4 }, { x: 4, y: 5 }, { x: 5, y: 5.5 }, { x: 6, y: 7 }], xRange: [0, 7], yRange: [0, 8], xLabel: '키(cm)', yLabel: '몸무게(kg)', gridStep: 1, showTrendLine: true },
  },
  {
    id: 'm3-2-stat-neg',
    name: '산점도 (음의 상관)',
    description: '음의 상관관계 산점도',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '통계',
    diagramType: 'scatter_plot',
    defaultParams: { points: [{ x: 1, y: 7 }, { x: 2, y: 6 }, { x: 3, y: 5 }, { x: 4, y: 3 }, { x: 5, y: 2.5 }, { x: 6, y: 1 }], xRange: [0, 7], yRange: [0, 8], xLabel: '거리', yLabel: '기온', gridStep: 1, showTrendLine: true },
  },
  {
    id: 'm3-2-stat-none',
    name: '산점도 (상관없음)',
    description: '상관관계가 없는 산점도',
    schoolLevel: 'middle',
    gradeKey: '3학년 2학기',
    chapter: '통계',
    diagramType: 'scatter_plot',
    defaultParams: { points: [{ x: 1, y: 5 }, { x: 2, y: 2 }, { x: 3, y: 6 }, { x: 4, y: 3 }, { x: 5, y: 7 }, { x: 6, y: 1 }], xRange: [0, 7], yRange: [0, 8], xLabel: 'x', yLabel: 'y', gridStep: 1, showTrendLine: false },
  },

  // ═══════════════════════════════════════
  // 중1 1학기 — 문자와 식 (polygon + 변수 길이)
  // ═══════════════════════════════════════
  {
    id: 'm1-1-polygon-house-var',
    name: '집 모양 오각형 (문자)',
    description: '교과서 0596(2) — 상단 삼각형+하단 직사각형. 길이를 변수 a, b로 표현',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자와 식',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 200 }, { x: 200, y: 200 }, { x: 200, y: 80 }, { x: 100, y: 0 }, { x: 0, y: 80 }],
      // 지붕 꼭짓점(2,3,4)은 90°가 아니므로 직각 표시하지 않음
      rightAngleMarks: [0, 1],
      splitLines: [{ from: 2, to: 4, style: 'dashed' }],
      regions: [
        { vertexIndices: [0, 1, 2, 4], fill: '#E0E0F0', label: '②' },
        { vertexIndices: [4, 2, 3], fill: '#FFEDD5', label: '①' },
      ],
      showLengths: [
        { edge: [0, 1], value: 'a' },
        { edge: [1, 2], value: 'b' },
        { edge: [2, 3], value: '2' },
      ],
    },
  },
  {
    id: 'm1-1-polygon-staircase-var',
    name: '2단 계단 (문자)',
    description: '계단 모양 둘레/넓이 — 변수 a, b 사용 (자동 italic)',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자와 식',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 120 }, { x: 200, y: 120 }, { x: 200, y: 60 }, { x: 100, y: 60 }, { x: 100, y: 0 }, { x: 0, y: 0 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5],
      fill: '#A7F3D0',
      showLengths: [
        { edge: [5, 0], value: 'a' },
        { edge: [0, 1], value: 'b' },
        { edge: [4, 5], value: 'a' },
        { edge: [2, 3], value: 'b-a' },
      ],
    },
  },
  {
    id: 'm1-1-polygon-l-var',
    name: 'L자 도형 (문자)',
    description: 'L자 6각형 — 변수 a, b, c, d (자동 italic)',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자와 식',
    diagramType: 'polygon',
    defaultParams: {
      vertices: [{ x: 0, y: 120 }, { x: 200, y: 120 }, { x: 200, y: 60 }, { x: 80, y: 60 }, { x: 80, y: 0 }, { x: 0, y: 0 }],
      rightAngleMarks: [0, 1, 2, 3, 4, 5],
      fill: '#DBEAFE',
      showLengths: [
        { edge: [5, 0], value: 'a' },
        { edge: [0, 1], value: 'b' },
        { edge: [1, 2], value: 'c' },
        { edge: [4, 5], value: 'd' },
      ],
    },
  },
  {
    id: 'm1-1-quad-split-var',
    name: '사각형 대각선 분할 (문자)',
    description: '교과서 0596(1) 스타일 — 직각 2개 사각형을 대각선으로 두 직각삼각형으로',
    schoolLevel: 'middle',
    gradeKey: '1학년 1학기',
    chapter: '문자와 식',
    diagramType: 'quadrilateral',
    defaultParams: {
      vertices: [{ x: 10, y: 40 }, { x: 120, y: 10 }, { x: 140, y: 110 }, { x: 20, y: 130 }],
      rightAngleMarks: [0, 2],
      sides: [
        { from: 0, to: 1, label: '5' },
        { from: 1, to: 2, label: '4' },
        { from: 2, to: 3, label: 'b' },
        { from: 3, to: 0, label: 'a' },
      ],
    },
  },
];
